### ISSUE TITLE
talk about "unconf" and domain name

### ISSUE THREAD

**Issue by whit537** [sustainers/website#10]
Gunner recommends against calling it an "unconf" because of baggage in the term. What else could we call it?

**Comment by piamancini** [comment]
what happened with this? I saw somewhere that we changed it, right?

**Comment by jdorfman** [comment]
@piamancini by EOD tomorrow, if there are no objections/suggestions we will go with those. cc: @whit537 @andrew @jerodsanto @gr2m

**Comment by BenJam** [comment]
One day there will be a .conf TLD. One day...

**Comment by jdorfman** [comment]
@BenJam yeah, the fact they created (and approved) `.rodeo` makes question the leadership of `www` and the interwebs as a whole.

**Comment by piamancini** [comment]
@jdorfman do you have the twitter account already?

**Comment by BenJam** [comment]
@jdorfman maybe we could repurpose it, like we did .io? sustain.rodeo does have a certain ring to it.

**Comment by jdorfman** [comment]
@piamancini no, I will just rename the current one if that is what everyone wants

**Comment by jdorfman** [comment]
@BenJam I was thinking `.org` so it doesn't get confused with a typical `.io` domain

**Comment by jdorfman** [comment]
✅  Domain
✅  Twitter
