### ISSUE TITLE
Build the agenda

### ISSUE THREAD

**Issue by whit537** [sustainers/website#102]
Per @alnermcgunn. Builds on #9 and ties in with #92.

[**Working Draft**](https://docs.google.com/document/d/1HF7QSijFe8U4Nja1McN1nWqXap7geM1dANiP5RVGPQY/edit#heading=h.6pnny5wzujrd)

**Comment by whit537** [comment]
General expectation (per private weekly call) is that sessions will coalesce around success stories, so, people on the demand side (project maintainers) who have found sustainability in one way or another will be sharing their experience with "everyone else" (ranging from "clueless" to "almost at the tipping point"). Secondary activity is to connect demand side with supply side (foundations and companies).

**Comment by whit537** [comment]
Per private weekly call @alnermcgunn heard back from a few folks but would like to see more engagement. Perhaps a reminder email mid-week (from whom?)?

One emerging question: how formally do we mean the word organization?

@piamancini will email intro sponsors to @alnermcgunn, since they are also participants.

@alnermcgunn to put together a "fictional agenda" and drop a Google Doc link here.

**Comment by whit537** [comment]
On @alnermcgunn to post agenda scaffolding.

**Comment by whit537** [comment]
Expecting 2 or 3 rounds of sessions, session size goal is 7-9 people.

**Comment by whit537** [comment]
Working draft: https://docs.google.com/document/d/1HF7QSijFe8U4Nja1McN1nWqXap7geM1dANiP5RVGPQY/edit#.

**Comment by whit537** [comment]
From @alnermcgunn in a private email thread:

> I have made good progress on a more believable agenda, thanks to Ben and Chad for great analysis of participant input.
>
> Speaking of which, we have gotten some more responses, and those are in the Participant Input gdoc now.
>
>Things we need to at this point:
>
> * I welcome reflections on participant feedback from other than Ben and Chad
> * We need to identify potential facilitators to tap.
> * Does anyone have a sense of our participant makeup? How many maintainers, how many funders, how many other and what types?

> One other thing to be thinking about: are there "exemplars" coming next week, projects that have compelling or unique approaches to "sustainability" in its many forms?

**Comment by jdorfman** [comment]
Closing, reopen if needed
