### ISSUE TITLE
Add Maintainer.io to Brought To You By list

### ISSUE THREAD

**Issue by RichardLitt** [sustainers/website#103]
Stub.

**Comment by jdorfman** [comment]
We will just add it to the sponsors page. Please attach your logo to this thread. TY

**Comment by RichardLitt** [comment]
Sorry, been traveling and haven't had much time at keyboard. I can still do this. If you're very worried about open issues: https://github.com/mntnr/website/blob/master/static/images/logo/mntnr%20smaller.png

Why not on the main page, too? :/ @mntnr isn't technically a sponsor, we're helping with organizing.

**Comment by RichardLitt** [comment]
@jdorfman Having issues converting the .png to .svg. Any ideas?

**Comment by jdorfman** [comment]
@RichardLitt can't convert png to svg, only the other way around. But we only need png in the case.

Do you have one that has text? Your logo would be the only one without context.

**Comment by RichardLitt** [comment]
![maintainer-with-words](https://cloud.githubusercontent.com/assets/910753/25952982/5a55d56c-3662-11e7-951d-5a015c6e5653.png)

Will that do?

**Comment by jdorfman** [comment]
Done 

![image](https://cloud.githubusercontent.com/assets/398230/25973842/b70bd246-365a-11e7-8799-bdc5f150d4d1.png)

**Comment by RichardLitt** [comment]
\o/ Thanks.
