### ISSUE TITLE
Get on track w/ email convos

### ISSUE THREAD

**Issue by whit537** [sustainers/website#105]
@alnermcgunn is planning to do 1-on-1 email conversations with registrants in the run-up in order to build the agenda (#102). This ticket is about level-setting.

- [ ] @piamancini to get @alnermcgunn emails of people who have already registered.
- [ ] @alnermcgunn to establish contact with people who have already registered.
- [ ] @piamancini to update ticket purchase confirmation with copy "Expect to hear from Gunner."
- [ ] @piamancini to feed email addresses of new registrants to @alnermcgunn.

Once we've got the process in place we can close this ticket, outcome of actual conversations will land on #102.

@piamancini @alnermcgunn Yes?

**Comment by alnermcgunn** [comment]
This is correct, and I put the email language at #104

**Comment by whit537** [comment]
@alnermcgunn Awesome, thank you. I'm folding #104 back into this ticket since there's not a clear separate action item there, and the content there relates clearly to the action item here. 🙇

> Below is some text to connect me to participants of the meeting.
> Please feel free to edit it to both make it your own voice and also correct anything I got wrong.
> If you could send individual emails to each registered participant (sorry for the hassle!) and cc me, I will reply to each, move you to BCC, and collect responses.
> Please let me know if all that makes sense, and thanks in advance!
> 
> 
>> Dear NAME,
>> 
>> We are looking forward to seeing you at Sustain in San Francisco on June 19.
>> 
>> I'm writing to introduce you to Allen Gunn (Gunner) of Aspiration, who is helping to plan and facilitate the event.
>> 
>> As we design and focus the event agenda, we are reaching out to each of the participants to better understand how this gathering can be most useful and relevant to the work you are doing.
>> 
>> I have cc'd Gunner on this email and he will be reaching out to you shortly with preliminary questions regarding your expectations of the event.  Please look out for his email and respond to his questions so that he can incorporate everyone’s feedback into his planning.
>> 
>> Thanks in advance for your input on the meeting, and please let us know if you have any questions.
>> 
>> Sincerely,
>> NAME

(s/NAME/@piamancini unless I'm mistaken. ;)

**Comment by whit537** [comment]
I just realized that I'm a dork and you made that ticket before I made this one. Sorry about that! 😊

**Comment by whit537** [comment]
I feel bad. Moving back to #104. 🐭
