### ISSUE TITLE
Put on SustainOSS

### ISSUE THREAD

**Issue by whit537** [sustainers/website#106]
This is a meta-ticket to manage prioritization across other tickets.

Deep-dive process docs from Aspiration: https://facilitation.aspirationtech.org/.

The understanding that is starting to coalesce for me (please chime in!) is that we have a sequence roughly as follows:

We drive registrations through email outreach (#56), supported by ads (#98) and blogs (#73).

We feed people to Gunner, who engages them 1-on-1 over email (#104) to craft the agenda (#102 ~= #92). Agenda-crafting proceeds right up through the event itself.

Travel assistance (#32) and childcare (#57) will take shape as registrations firm up.

During the event itself, Changelog will work around the agenda to contribute interviews (#55), and of course there will be stickers (#88). ☺️

**Comment by whit537** [comment]
So the top priority I'm seeing right now is #56, driving registrations through email outreach.

**Comment by whit537** [comment]
We have a travel fund!

https://sustainoss.org/travel-support/

The deadline to apply is May 26: 17 days hence. The set of people we want to be intentional about reaching out to one-to-one overlaps strongly with the set of people who would be interested in and eligible for the travel fund, so I think we should have that May 26 deadline in mind with 1-to-1 outreach (#56) still our top priority.

**Comment by whit537** [comment]
Top priority this week is finishing up outreach on #56. Probably starting next week we should start looking at our funds available and making some decisions about how to spend it.

**Comment by whit537** [comment]
Top this week:

- travel fund: #113
- reading participant input and thinking about sessions: #92

**Comment by whit537** [comment]
Top this week:

- email session suggestions to @alnermcgunn: #92
- announcing decisions on travel fund: #113

**Comment by piamancini** [comment]
Top this week:
- Sloan sorted. @BenJam it seems we sloan is taking longer than expected. Should we be concerned?
- build de agenda & breakout sessions to be posted online next week.

**Comment by whit537** [comment]
Travel is tight!

Priority this week is agenda for @alnermcgunn: #92.

AND ALSO HAVING SUsTAIN!!!!!!!!! 🙉 😻

**Comment by jdorfman** [comment]
closing, reopen if needed
