### ISSUE TITLE
finalize the date

### ISSUE THREAD

**Issue by whit537** [sustainers/website#11]
I believe May 22 or maybe 23 is the current proposal.

**Comment by whit537** [comment]
Here's [the vote](https://opencollective.slack.com/archives/sustainunconf/p1484948584000671) we had in Slack (inlining screenshot ahead of eventual archive clippage; #12). Gunner prefers Monday. @thelarkinn Is May 22 a definite no for you or was it that May 23 was simply preferred?

![screen shot 2017-01-26 at 1 25 54 pm](https://cloud.githubusercontent.com/assets/134455/22344686/0d07ac3e-e3cb-11e6-94a2-86555e6a8148.png)

**Comment by TheLarkInn** [comment]
That date will/should work.

**Comment by jdorfman** [comment]
So May 23rd?

**Comment by whit537** [comment]
May 22, I think?

**Comment by jdorfman** [comment]
@piamancini @whit537 let's finalize Monday. Looks like the 23rd has more votes plus we could partner with https://2017.devxcon.com/ on marketing efforts since they are the 22nd.

**Comment by piamancini** [comment]
agreed!

**Comment by piamancini** [comment]
from Bandon Keeper (GH) on the date: 

> Unfortunately the big event space at GitHub HQ is only available for on Mondays and Wednesdays. If it's a smaller group (<20) we could probably find another space.

**Comment by piamancini** [comment]
I asked Gunner and he can do the 24th as well which is a Wed. 
Pros: we get big space in GH, 
Con: we don't piggy back as much on devxcon
The other option is to overlap with devxcon on monday, which I think is worse.

**Comment by jdorfman** [comment]
@piamancini 24th it is. The pros outweigh the cons IMO

**Comment by jdorfman** [comment]
May 22nd: "Hooray"
May 24th: "Heart"
