### ISSUE TITLE
Clarify relationship between two ways to buy tickets

### ISSUE THREAD

**Issue by whit537** [sustainers/website#112]
I can buy a ticket in two places. Are they the same? Are we bifurcating our registrant list?

cc: @piamancini 

# https://opencollective.com/sustainoss

![screen shot 2017-05-09 at 2 46 14 pm](https://cloud.githubusercontent.com/assets/134455/25869537/472221e6-34c6-11e7-965a-6ec9a200907c.png)

# https://opencollective.com/sustainoss/events/2017

![screen shot 2017-05-09 at 2 47 07 pm](https://cloud.githubusercontent.com/assets/134455/25869565/64c0833c-34c6-11e7-99b1-2d02eec63fee.png)

**Comment by whit537** [comment]
Can we just yank the first, @piamancini? It also points to the old slack.

**Comment by piamancini** [comment]
Yep, can do. It doesn't bifurcate. They are all in the collective.

**Comment by piamancini** [comment]
Updated the collective, added link to purchase tickets, website, etc.
