### ISSUE TITLE
Mass email night before

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#114]
I think it would be wise to send an email to all those who are signed up via OpenCollective. The email should contain the following:

* Time
* Address
* Cell Numbers (Pia, Chad, Justin, etc)
  * Text or call us if you need anything
* Link to COC
* Iron.io after party details

**Comment by RichardLitt** [comment]
Sounds good to me!

**Comment by whit537** [comment]
Per private weekly call, planning to use OC's email feature for this to reach all actual registered attendees.

**Comment by jdorfman** [comment]
Draft (cc @whit537 @piamancini):

Hello %name%,

A friendly reminder that Sustain is tomorrow morning! Registration & Breakfast starts @ 8am. View the entire schedule here: https://sustainoss.org/agenda/

The address to the venue is: 

GitHub
88 Colin P Kelly Jr St. 
San Francisco, CA 94107

You can also view it on Google Maps: https://goo.gl/maps/iT1GhEnW82A2

If you need anything please contact hello@sustainoss.org and all 3 event organizers will be notified immediately.

We have a Code of Conduct (C.o.C.) and will be enforcing it. There will be zero tolerance for ANY harassment of participants in any form. Please read it: https://sustainoss.org/code-of-conduct/

Last but not least there will be a Happy Hour after the event (still at GitHub). Please drink responsibly and note that the C.o.C. still stands.

We look forward to meeting you tomorrow. Thanks for your support!

**Comment by whit537** [comment]
Does it make sense to send this out Friday since the event is on a Monday?

**Comment by jdorfman** [comment]
@whit537 lets take a poll on the call

**Comment by jdorfman** [comment]
- [ ] Send Friday
- [ ] Export from @piamancini

**Comment by piamancini** [comment]
Invite folks who are already in the area to get together on Sunday
Options in the area: 
- Bowling! http://www.bowlluckystrike.com/locations/san-francisco/
- Brewery http://21st-amendment.com/
I vote bowling, could be fun. 
I also emailed Dylan from iron.io to see if they'd like to sponsor some drinks then.

**Comment by piamancini** [comment]
@jdorfman email reads great, 
would change it so we can send it on Friday 
add Sunday drinks 
maybe also add a note saying: There will be someone taking pictures, if you don't want your photo taken, we'll be handing out red dots to stick on your name badge. We ask everyone to respect the wishes of those who are displaying a dot.

**Comment by jdorfman** [comment]
@piamancini @whit537 Here: https://docs.google.com/document/d/15mvQ-pB2AF351MOMKj-5UWDsOrirWr2lUBE6tjbxbqg/edit

**Comment by whit537** [comment]
Per https://github.com/sustainers/website/issues/121#issuecomment-306962075 I believe we should expect red lanyards, not red dots. Doc revised.

**Comment by jdorfman** [comment]
@whit537 good catch, ty
