### ISSUE TITLE
Hire photographer

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#117]
talk to Adam

**Comment by whit537** [comment]
Discussing on private weekly call. What are our goals? Building community. Communicating to those who couldn't make it that this was an event worth being at—next time!

**Comment by whit537** [comment]
More cost efficient to find someone in SF.

**Comment by whit537** [comment]
Context: Adam has someone in Austin that he recommends. Decision on private weekly call is to put his name in the travel fund hat and decide as part of that.

**Comment by whit537** [comment]
@piamancini checking with @nayafia for local reference.

**Comment by nayafia** [comment]
I mentioned to jdorfman that if you let me know what the budget is and what type of work you'd need, I can ask a few people at GitHub. I imagine hiring locally is more cost efficient than flying a photographer in.

**Comment by jdorfman** [comment]
@nayafia sorry I am traveling, it was on my notes for today's call but I couldn't make it. Sorry for letting this fall throw the cracks.

**Comment by nayafia** [comment]
np! I'll also add:

Given the group size and unconference nature, you may not need a professional photographer at all. Maintainerati didn't have one, in fact it probably will make people feel more comfortable being candid without one. Just a thought :)

**Comment by jdorfman** [comment]
@nayafia good point. The more money we save, the more money we can donate or use to fund another event down the line.

**Comment by piamancini** [comment]
oh damn! I missed this. I thought we were still looking for one. I've asked Adam to confirm Ben. I'll stop it now. 
Sorry everyone, completely missed this ticket.

**Comment by adamstac** [comment]
Our photographer @bengillin is very personable and is experienced enough to not make folks uncomfortable. In the case of this event, he'd use a lens that doesn't require him to be in people's faces. Instead he'd remain out of the way to try to capture the scene and community nature of this event.

It was my suggestion to have him there -- to be able to share with the rest of the community who can't make it, what's it was like to be there, the community feel, and to make it easier to visualize things for future iterations of this.

We're not talking about paparazzi here.

**Comment by whit537** [comment]
I call a vote!

👍  Yes, bring Ben!
👎  No, don't bring Ben!

**Comment by piamancini** [comment]
@adamstac thank you so much for the patience and understanding. let's do this!

**Comment by whit537** [comment]
Caveat is that we will need to make sure badges (#121) have "no photos" clearly indicated and @bengillin is aware.

**Comment by jdorfman** [comment]
@whit537 we should have circles e.g. 
* Red = NO 
* Yellow = Ask
* Green = YES

**Comment by adamstac** [comment]
No worries @piamancini, I know making decisions around things like this can get nuanced. Thanks yall.

I'll make sure we get Ben's ticket and hotel soon and we'll follow up on the best way to submit the expense.
