### ISSUE TITLE
log slack

### ISSUE THREAD

**Issue by whit537** [sustainers/website#12]
It's helpful to be able to cross link Slack conversations in GitHub issues to give full context ([e.g.](https://github.com/sustainers/website/issues/11#issuecomment-275469883)), but the Nothing is already eating us. [SlackArchive](http://slackarchive.io/) is the best solution I've found, though it's a bit rough around the edges.

![screen shot 2017-01-26 at 1 23 07 pm](https://cloud.githubusercontent.com/assets/134455/22344691/12524b54-e3cb-11e6-8141-4e9a06af2fb1.png)

**Comment by jdorfman** [comment]
Don't think it is that important. Going forward everything actionable will be on GitHub. Closing for now.
