### ISSUE TITLE
Reserve a bar

### ISSUE THREAD

**Issue by whit537** [sustainers/website#120]
Iron.io wants to sponsor after-event drinks. We should have them reserve space at a bar near GitHub. Suggestions in slack:

- Lord George
- Woodbury
- Black Hammer Brewery
- Garaje

**Comment by whit537** [comment]
@piamancini to work this one through with Iron.io and GitHub.

**Comment by whit537** [comment]
Per @piamancini who talked to @bkeepers we are good to keep this at GitHub.

@piamancini to follow up with Dylan from Iron.io.

**Comment by jdorfman** [comment]
Cool I will close for now.
