### ISSUE TITLE
Name Badges

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#121]
I am thinking that we have custom name badges (die cut stickers) printed up. Maybe have the sponsors underneath? We can bring a Sharpie or export a CSV and print them on clear labels to put on the badge/sticker.

![image](https://cloud.githubusercontent.com/assets/398230/26501474/9ba34c60-41ee-11e7-95d9-acdf0d672c7d.png)

Thoughts?

**Comment by whit537** [comment]
@alnermcgunn is offering to handle this, he has templates and strong opinions. ☺️

**Comment by jdorfman** [comment]
@whit537 cool.

@alnermcgunn what are you thinking?

**Comment by whit537** [comment]
IIRC:

- "mid-torso" lanyard
- only thing on it is first name
- except maybe an event logo
- nothing special to differentiate, e.g., sponsors

In other words, nearly the opposite of my OSCON badge. ☺️

![flair](https://cloud.githubusercontent.com/assets/134455/26655953/0759937a-462b-11e7-90a2-ea845a6d1105.jpg)

**Comment by whit537** [comment]
From @jdorfman at https://github.com/sustainers/website/issues/117#issuecomment-306538232 re: photo consent:

> we should have circles e.g.
> 
>Red = NO
Yellow = Ask
Green = YES

**Comment by piamancini** [comment]
want to close this by 13th. 
- red dots for no photographs 
- stickers
- ask github if they have lanyards (@nayafia @bkeepers)

**Comment by nayafia** [comment]
> ask github if they have lanyards (@nayafia @bkeepers)

Just asked, we don't unfortunately :(

**Comment by jdorfman** [comment]
Thanks for checking @nayafia 

@piamancini the 13th is cutting it too short. The 9th (Friday) is best.

@alnermcgunn can I just have my designer make something and get feedback from there?

**Comment by whit537** [comment]
@jdorfman I suggest emailing @alnermcgunn, because I'm not sure he checks his notifications. Track him down and make this happen.

**Comment by alnermcgunn** [comment]
Sorry to be late to this thread. We can provide lanyards red and other. I recommend 2 colors (pictures ok/no pictures), 3 complicates things without adding much value IMO.

I'm fine to have name tag mocked up. My main opinion is that is that participant-specific data should be first name only, largest font possible. No last name, no title, no company. Our approach is to set expectation that folks have to talk to one another to get that data. Also avoids awkward staring-at-chest protocols.

Attached is our name tag template so you can see how we roll.
[AspirationEventNametagTemplate.pdf](https://github.com/sustainers/website/files/1059633/AspirationEventNametagTemplate.pdf)

**Comment by jdorfman** [comment]
@alnermcgunn 

> Sorry to be late to this thread. 

all good.

>We can provide lanyards red and other. I recommend 2 colors (pictures ok/no pictures), 3 complicates things without adding much value IMO.

That would be great! Does that include the plastic?

> I'm fine to have name tag mocked up. My main opinion is that is that participant-specific data should be first name only, largest font possible. No last name, no title, no company. Our approach is to set expectation that folks have to talk to one another to get that data. Also avoids awkward staring-at-chest protocols.

👍

> Attached is our name tag template so you can see how we roll.

Looks great. @piamancini and her crew created a new feature that will streamline this process. See https://github.com/opencollective/frontend/pull/15

**Comment by alnermcgunn** [comment]
Yes, we can provide the plastic. I'm even glad to have my team assemble them once there is a template similar to the one linked above.

**Comment by xdamman** [comment]
FYI We know offer a way to export the list of attendees as a PDF with name tags, e.g. https://opencollective.com/sustainoss/events/2017/nametags.pdf

See the PR if you'd like to adapt it to a different format https://github.com/opencollective/frontend/pull/15

**Comment by jdorfman** [comment]
@alnermcgunn is this good to go?

**Comment by whit537** [comment]
> is this good to go?

It doesn't feel like it to me. These need to get stuffed tomorrow or Friday in time for Monday. I suggest we call/email @alnermcgunn to make sure we are squared. I will try to remember to do so tomorrow if someone else doesn't get there first.

**Comment by jdorfman** [comment]
@whit537 we are on it. I cc'd you on last email

**Comment by whit537** [comment]
Not seeing yer mail but I trust you. :-)

!m @jdorfman 💃

**Comment by jdorfman** [comment]
@whit537 sent to your gmail

**Comment by jdorfman** [comment]
"Fwd: Re: TIME SENSITIVE: Please test this name tag design"

**Comment by whit537** [comment]
Ah, that's why! I don't see mail to whit537@gmail.com unless I dig for it. chad@gratipay.com is best in future. ☺️

**Comment by xdamman** [comment]
Did I write "know" instead of "now". OMG 😱

**Comment by jdorfman** [comment]
via @alnermcgunn "We are all set, name tags are printed and assembled."
