### ISSUE TITLE
Post agenda on website

### ISSUE THREAD

**Issue by whit537** [sustainers/website#124]
From @alnermcgunn in private email:

> I think we can put the time splits/session names on the site now, just leave out the descriptive text. Let me know if that's a clear distinction.
>
>The stuff that is on the site is definitely inaccurate. Also, it has us starting agenda at 10, not 9. If we are going to try and start at 9, we should correct that as soon as possible.

Referring to [working draft](https://docs.google.com/document/d/1HF7QSijFe8U4Nja1McN1nWqXap7geM1dANiP5RVGPQY/edit#heading=h.6pnny5wzujrd) on #102.

**Comment by jdorfman** [comment]
Updated: https://sustainoss.org/agenda/
