### ISSUE TITLE
Decide how to spend general funds

### ISSUE THREAD

**Issue by whit537** [sustainers/website#125]
Our [current balance](https://opencollective.com/sustainoss) on OC is $6,730.58 and is likely to grow by a bit with last-minute registrations. The decision at  https://github.com/sustainers/website/issues/113#issuecomment-305798064 seems to be that the travel fund is under control and we don't need to dip into our general funds to backfill the travel fund.

How should we spend the money we're collecting?

**Comment by whit537** [comment]
I propose that it be available to core organizers to reimburse our own travel, beyond what CII is able to cover.

**Comment by jdorfman** [comment]
Fortunately, my travel is covered, but I agree that **core** organizers should be reimbursed.

**Comment by jdorfman** [comment]
I think giving it to package managers would have the biggest impact. Although maybe we should consider the documentation community. It was the top encountered problem in the [Open Source Survey 2017](http://opensourcesurvey.org/2017/)...

![image](https://cloud.githubusercontent.com/assets/398230/26805904/21afb9bc-4a03-11e7-9efb-3af449ffa850.png)

**Comment by whit537** [comment]
Per private weekly call, we are keeping this open through the event. Paying for core organizer travel is on the table. We are also seeing risk in the travel fund (#113) and want to hold cash against that. Third thing would be retaining some earnings to jumpstart the next event.

**Comment by piamancini** [comment]
Pia, Ben (photo) & Chad's ticket to be funded from this. 
We'll leave a buffer just in case. 
There was an idea of using what's left for next event.

**Comment by whit537** [comment]
No objections on today's private weekly call for me to expense my travel (covered by LLNL @tgamblin per slack—thank you!).

Otherwise we are keeping this open until post-event.

**Comment by tgamblin** [comment]
Note: we're still waiting for official approval for sponsorship, but yes this is the intent. LLNL needs receipts for the flight and lodging as well, so please keep those.  Sorry this is tedious!

**Comment by jdorfman** [comment]
Maybe ask the attendees how we should spend the funds?

**Comment by jdorfman** [comment]
Another issue that should be moved to sustainers/discussions. 

* All in favor 👍 
* Leave it here 👎

**Comment by whit537** [comment]
Closing here. Rather than open a general discussion on the new repo, let's just let this lie until someone has a specific proposal.
