### ISSUE TITLE
Introduce yourself

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#128]
👋  I'm [Justin](https://www.justindorfman.com/). I am an Open Source sustainer, maintainer, and contributor. I currently work for [Sticker Mule](https://www.stickermule.com/uses/laptop-stickers) doing Developer Relations. They have been awesome enough to let me organize this event with @piamancini @whit537 @andrew @jerodsanto @BenJam @alnermcgunn @RichardLitt & many others.

I look forward to meeting you all on the 19th. I also really love [our sponsors](https://sustainoss.org/sponsor/) for making this all happen.

How about you?

**Comment by gr2m** [comment]
Hey everyone 👋 I like to call myself community facilitator at [Hoodie](http://hood.ie/) – the friendly JavaScript backend for offline-first applications. Since the first day of Hoodie we were thinking about how to make the project sustain itself while remaining independent (including from [us](https://neighbourhood.ie)). We made some great progress but have a lot to figure out. We shared our thoughts at http://hood.ie/blog/sustaining-hoodie

I’m looking forward to meet you all in San Francisco on June 19th!

**Comment by BenJam** [comment]
👋  I'm Ben, BenJam pretty much everywhere. I work with @andrew as the product guy at Libraries.io, which came about through my work on protecting core internet infrastructure. I'm pretty focussed on supporting digital infrastructure-type projects, picking up on the work @nayafia did with Ford last year.

**Comment by andrew** [comment]
Hi, I'm Andrew 👋 

I've been working on [Libraries.io](https://libraries.io) for the past couple years funded by Sloan and Ford Foundations, connecting the dots between open source projects and building tools on top of that data to help people discover, maintain and sustain open source software better.

Coming over to Sustain from the UK with @BenJam to see how we can best help find the open source projects that we as a community need to sustain the most and help support them better.

Also ask me about my miniature poodles! 

![14583408_1233954806645721_3926156311103799296_n](https://user-images.githubusercontent.com/1060/26885583-f19648ba-4b9a-11e7-9473-75943c51cac3.jpg)

**Comment by jerodsanto** [comment]
Jerod here 👋 

I make podcasts and stuff at [Changelog.com](https://changelog.com). We 💚 open source software and the people who create it, so helping out with Sustain was a no-brainer for me.

I'm excited to hang out and record some conversations with folks at the event so we can share our learnings and experiences with the greater community that cannot attend.

**Comment by kborchers** [comment]
👋 

I am Kris Borchers, working for the [Linux Foundation](https://linuxfoundation.org) running the [JS Foundation](https://js.foundation). My focus is long-term sustainability for open source projects with a focus currently on the open source JavaScript ecosystem. Looking forward to great conversations!

**Comment by RichardLitt** [comment]
👋  🐉  👋  Hey friends. I am [@richlitt](https://twitter.com/richlitt). I run maintainer.io (@mntnr), helping developers and companies maintain and scale out their open source code. I'm interested in alternative models for financing open source, and in helping out with a good work/life balance for those in open source. 

Looking forward to seeing you all in SF!

**Comment by piamancini** [comment]
Hi peeps! I'm Pia (@piamancini) one of the founders of Open Collective. Previous life in civic tech, politics and democracy activism - which I still do! Working on building infrastructure for open collectives around the world to have economic power and a viable organizational scheme. Looking forward to connecting AFK with y'all. <3

**Comment by jashmenn** [comment]
👋  I'm Nate [@eigenjoy](https://twitter.com/eigenjoy) and a co-author of the books [Fullstack React](https://www.fullstackreact.com/), and [ng-book](https://www.ng-book.com/2/). Previously I worked at IFTTT.

I've been [thinking](https://twitter.com/eigenjoy/status/862412458517962752) [a lot](https://news.ycombinator.com/item?id=14446871) about how we can better fund OSS. I believe that there is a lot of valuable software that isn't being written (or maintained) because none of the models are quite right.

If you write software that gets used, then it should be easy to get paid. But almost all of the current models require that you essentially take on a second job.

I've been toying with e.g. Bitcoin on and off since 2011 and I think that blockchain apps (obviously) have a role to play in this space. I'm working on a few ideas here that I'd love to chat about.

Looking forward to meeting you all!

**Comment by mikeal** [comment]
:wave: I'm Mikeal.

I've been a community organizer in Node.js since the early days. I helped start the Node.js Foundation lead it for the first few years.

I co-host a podcast with Nadia about Open Source Sustainability called [RFC](rfc.fm) and I write quite often about the subject [on Medium](https://medium.com/@mikeal).

**Comment by gabelula** [comment]
Hi! I'm @gaba. I have been a software developer at The Coral Project for the last (almost) two years. We are working on open source tools to make and moderate comments as well as working on community around journalism. 

I'm very interested in different models of sustainability around open source projects as well as how to bring this into journalism.

**Comment by dasilvacontin** [comment]
Hi everyone! Greetings from Barcelona~ o/

I'm David. I've been a maintainer at [Mocha.js](https://github.com/mochajs/mocha/) for close to 3 years now, together with some other nice peeps ❤️. We have problems (and had discussions) about "maintainer motivation & churn" and "how to best spend our monies". I'm also interested in inclusivity and open government.

Looking forward to meeting you all and having great discussions! ❤️

**Comment by ericholscher** [comment]
Hey all!

I'm Eric. I've been active in the Python/Django community for over 10 years now, and have been working primarily on/in open source for the past 5 years. The main things I'm doing:

* Working full time on [Read the Docs](https://github.com/rtfd/readthedocs.org) trying to make it sustainable
* Helping lead the [Write the Docs](http://www.writethedocs.org/) community -- a global community focused on documentation. Also trying to figure out sustainability in that context.
* A (newly elected 😨) director of the Python Software Foundation -- where we are looking at possible institutional mechanisms for funding OSS, similar to [Ruby Together](https://rubytogether.org/)

I have a lot of different perspectives around sustainability, from event organizing, open source services, infrastructure in OSS, and lots of other things. Looking forward to chatting!

**Comment by alanapost** [comment]
Hello! :wave:

I'm Alana, working on product at [The Linux Foundation](https://www.linuxfoundation.org).

Like @kborchers and many others, I'm very interested in sustainability.

Looking forward to meeting/learning from folks!

**Comment by bwaliszewski** [comment]
Hi,
I'm Betsy from the Python Software Foundation. I would like to hear from others, how they manage volunteer motivation and recruitment for remote tasks. Also, how do they deal with succession planning for volunteer tasks. Accessibility for beginners to contribute to OSS! This informs capacity building and should be an instrumental effort. Getting started seems to be the number one stumbling block for those wanted to participate/contribute.

Can't wait to meet everyone!

**Comment by andreagoulet** [comment]
Hi, everyone! I'm @andreagoulet, CEO [Corgibytes](http://corgibytes.com). My business partner (@mscottford) and I are really looking forward to the event. We're a software consultancy built around the idea that there are folks who love making existing code better. We call ourselves a group of "menders" who love "software remodeling" and we love working on OSS. 

We're trying to find a way to make open source projects a bigger part of our portfolio. We've thought of a few different business models and [wrote a blog about it recently.](http://corgibytes.com/blog/2017/05/29/open-source-sustainability/)

Looking forward to seeing everyone!

**Comment by ljharb** [comment]
Hi! I'm @ljharb. I work at @airbnb on Web Infrastructure, and manage airbnb's Open Source in general. I'm also a member of @TC39.

I maintain a number of open source projects, including [nvm](http://nvm.sh), [enzyme](http://airbnb.io/enzyme/), [eslint-config-airbnb](https://github.com/airbnb/javascript), [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react), [qs](https://github.com/ljharb/qs), [es5-shim](https://github.com/es-shims/es5-shim) and [es6-shim](https://github.com/paulmillr/es6-shim), [tape](https://github.com/substack/tape), etc - so sustainable OSS is pretty top-of-mind for me.

Excited for the event!

**Comment by nayafia** [comment]
Hi! :wave: I'm Nadia. I've [written a bunch of things](http://nadiaeghbal.com/oss) about open source and sustainability, and I also [co-host a podcast](https://changelog.com/rfc) about it. I work at GitHub on our open source team. :tada:

Look forward to meeting you all soon!

**Comment by blakeembrey** [comment]
Hi, I'm Blake. I've been involved with OSS heavily since I started node.js a few years ago. Some of this lead me to do a lot of things around TypeScript in the past couple of years, as well as getting involved with Express.js and many other JS modules I maintain (including many I've adopted from someone else). I'm excited to hear what people have to say about sustainable OSS, it's a topic that's been heavy on my mind over the last year.

**Comment by havocp** [comment]
Hi, I'm Havoc. I've been working at OSS-based companies for 18 years (Red Hat, litl, Typesafe/Lightbend, Continuum).

I've mostly been at funded companies but I've spent a lot of time exploring 1-person bootstrap/"solopreneur" options and I'm very interested in how to construct smaller-scale businesses that sustain OSS projects.

Most of my OSS code still predates GitHub. But I have a fairly popular Java library on here ( https://github.com/typesafehub/config ) and recently I've been the primary dev for a new Python tool related to Continuum's Anaconda ( https://github.com/Anaconda-Platform/anaconda-project ). Pre-GitHub-era I mostly wrote Linux OS stuff like GNOME pieces and D-Bus.

Have read and listened to a lot of attendees online and look forward to meeting people in person. Please say hi!

**Comment by penelopeyao** [comment]
Hi hi!  My name is Penny and I look forward to learning  about sustainability in addition to open source in general.  I'm currently at the Linux Foundation (and fairly new) and most of my tech experience has been on the start-up side.  Along with @jashmenn I'm interested in the topic of how to help sustain important projects, especially when they fall "out of trend."

**Comment by jdorfman** [comment]
Closing and locking this. Go here: https://github.com/sustainers/discussions/issues/1
