### ISSUE TITLE
Event Marketing

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#13]
WIP

- Link backs
  - [ ] Awesome JSON Datasets #71
- Podcast
  - [ ] Elevator pitch
  - [ ] Changelog - @jerodsanto 
  - [ ] RFC - @piamancini _not sure if they planned season 2 out yet_ cc: @jerodsanto 
- Blog post
  - [x] Opensource.com - @jdorfman (goes live 4.6.17 at 3am ET)
  - [ ] Gratipay News - @whit537 #70
  - [ ] GitHub Blog - Brandon Keepers
- Twitter
  - [x] Setup OpenCollective auto tweet
  - [x] Rename?
  - [x] `#hashtag`:
    - [x] `#sustainoss`
  - [x] Schedule tweets
    - [x] Thank GitHub
    - [x] Thank StackPath
    - [x] Thank Sticker Mule
    - [x] Thank ...
- Answers for FAQs
  - [ ] What is $ustainOSS?
  - [ ] How is it written? (Sustain OSS, $ustainoss, $ustainOSS, $ustain OSS)
  - [ ] How many people will be there?
  - [ ] What is the price?
  - [ ] Will you have discounts for students?
  - [ ] What will you be serving for lunch?
  - [ ] Will there be talks?
  - [ ] How many days is it?
  - [ ] Will there be hotel accomidations?
  - [ ] Will there be other events in different countries?
  - [ ] Do you accept in-kind sponsorships?
  - [ ] When will I receive a ticket?
  - [ ] What other events can you compare $ustain OSS to?

**Comment by jdorfman** [comment]
OpenSource.com blog post has been sent to the editor, should be live next week.

**Comment by whit537** [comment]
@jdorfman Who is your editor at OpenSource.com?

**Comment by whit537** [comment]
I am [planning](https://github.com/gratipay/inside.gratipay.com/issues/948) to be at OSCON/CLS, can help promote there.

**Comment by jdorfman** [comment]
@whit537 Jen Wike Huger

**Comment by whit537** [comment]
Talking on (private) working call w/ @jdorfman @RichardLitt, plan is to see how much traction we get from the OpenSource.com piece and follow-on organic Twitter marketing, will evaluate signups after a few weeks and decide on more formal promotion steps.

**Comment by jdorfman** [comment]
@whit537 @RichardLitt the newsletter signup will be a great funnel. Looking forward to getting it set up today.

**Comment by RichardLitt** [comment]
Should we make the FAQ page based on those questions? I see some unchecked boxes above; split out into their own issues?

**Comment by whit537** [comment]
I say follow your heart, @RichardLitt. :-)
