### ISSUE TITLE
Produce outputs

### ISSUE THREAD

**Issue by whit537** [sustainers/website#132]
@alnermcgunn directed participants to send notes to himself, myself, @piamancini & @jdorfman. I've received a couple submissions so far. What's our plan for those? Dump to Google Drive? With what sharing?

**Comment by RichardLitt** [comment]
I think putting them in a GitHub repo makes more sense, to me. We can make a repository for the event notes. That way it is closer to any ongoing discussions on sustainers/discussions.

**Comment by jdorfman** [comment]
@whit537 start with Google docs so we can leave comments and such. @RichardLitt send me your gmail and I will add you to the folder. Will need your help with this.

Once the notes are processed we can then make the report more democratic and crowdsource-able.

**Comment by whit537** [comment]
Notes folder started here:

https://drive.google.com/drive/u/2/folders/0B4Pn7wQ5iaKQZjhzX2NfbS1vWmc

**Comment by whit537** [comment]
@piamancini suggests at https://github.com/sustainers/website/issues/133#issuecomment-310357527 that we hire someone to process the raw outputs from the event.

**Comment by RichardLitt** [comment]
I think that is a good idea. Writing up notes will be pretty time intensive. Do you know where we could find someone to do this, though?

**Comment by whit537** [comment]
@jdorfman shared a folder with me called Sustain Data that has a lot more stuff in it. I've added it under the main Sustain folder and have folded the other Notes folder into it.

https://drive.google.com/drive/u/2/folders/0BwzjZpa-s_3acXQ2ZVZqX0RhZ0U

**Comment by whit537** [comment]
Per small private call (@alnermcgunn @piamancini @jdorfman @whit537):

1. send out message "We're typing up notes, get in touch if you want to help with that. Also, opt-out on participant list."
1. retake pictures of notes pages as needed
1. organize photos with filenames per the agenda
1. hire someone to transcribe, prioritizing:
    1. "Where from here?"
    1. lists
    1. etc.
1. organize a folder and share the transcripts and photos with the community
    - invite review for consent and redaction
1. write up agenda as it happened

Once notes are typed up revisit the idea of writing up a summary report/blog post. Share redacted transcripts/photos publicly.

**Comment by piamancini** [comment]
- emailed everyone who took notes 
- added the notes on docs on the folder, sustainability discussion, breakout 1(morning) and breakout 2 (afternoon).
- Connected with Will for hiring him to do this.
- @RichardLitt volunteered to do some of the activity posters so we can ship them ASAP. We could use some more hands. 

@jdorfman: I think it's worth adding to the email the following: 
"Please those who have notes, don't forget to send them to hello@sustain.org, everything helps!"
(We should start another issue for the email if you want, might be easier)

**Comment by RichardLitt** [comment]
Done: https://docs.google.com/document/d/1HflUrwj6mIZdjMOu1a3YbOxVUp5mqyV5jmEcKha16os/edit?usp=sharing

**Comment by jdorfman** [comment]
Email

List: Attendees
Subject: Next steps
Body:

Hello %name%,

For those who filled out the survey, we thank you! If you haven't yet [please do](ttps://goo.gl/forms/EpNG6CsEsvtjCICy1).

**We need your help with 2 things.**

1. **Please send us any notes you took for:** sustainability discussion, breakout 1 (morning) and breakout 2 (afternoon) by emailing thenotes @ sustainoss.org
2. **Before we send you a PDF with everyone's name and email** who attended Sustain we would like to give you the option to opt out. If you wish for your name & email to be removed from the list please email nolist @ sustainoss.org

The information will be distributed under the following usage and privacy terms:

* The list is provided for one-to-one and one-to-several communications
* It is not ok to promote/spam the entire list of addresses for any reason
* It is not ok to auto-subscribe addresses from the list to other mailing lists
* It is not ok to forward or redistribute the participant list to any non-participant in any form

You will have by 6pm PST Monday (06-31-2017).

Thanks!

**Comment by alnermcgunn** [comment]
Will we also share affiliation? We normally share that as well.

Also, might make sense to have "Sustain" in the subject line?

"You will have by 6pm PST Monday (06-31-2017)." --> "We will send the participant list by 6pm PST Monday (06-31-2017)."

Otherwise looks excellent, thanks!

**Comment by whit537** [comment]
Yinz are doin' so great. :clap:

Thanks for transcribing all those post-it notes, @RichardLitt! :scream_cat:

**Comment by RichardLitt** [comment]
> Thanks for transcribing all those post-it notes, [@RichardLitt](https://github.com/richardlitt)! <g-emoji alias="scream_cat" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f640.png" ios-version="6.0" title=":scream_cat:">🙀</g-emoji>

Only the poster 'next steps' papers, I'm afraid! There's a lot more post it notes things to do.

**Comment by jdorfman** [comment]
@tieguy posted his notes: https://gist.github.com/tieguy/02764b57e430739c999e6f0b5eb40c6e

In the future, we should use [discussions](https://github.com/sustainers/discussions/) instead of sustainers/website to avoid confusion.

**Comment by whit537** [comment]
Closing in favor of https://github.com/sustainers/discussions/issues/2.
