### ISSUE TITLE
Send out survey

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#133]
- [x] Create MailChimp Account (for segments)
- [x] Import _**attendee**_ list
- [x] Finialize copy
- [x] Create Survey with Google Forms (@alnermcgunn has template)
- [x] Setup forwarding on mailgun
- [x] Change `hello@` Gravatar
- [x] Send survey (to attendees only)

**Comment by jdorfman** [comment]
Imported: https://cl.ly/1r3p1S1B003G

**Comment by jdorfman** [comment]
![image](https://user-images.githubusercontent.com/398230/27391366-adc70d9a-5658-11e7-820b-336f545dd95d.png)

**Comment by jdorfman** [comment]
Example questions:

- https://www.fourthwallevents.com/10-questions-to-ask-on-your-post-event-survey/
- https://www.formstack.com/blog/2014/post-event-survey-questions/

**Comment by whit537** [comment]
From @jdorfman in private email:

> Gunner sent me the feedback template. I will plug his questions into this asap: https://docs.google.com/forms/d/e/1FAIpQLSeDZtHgFE5haH_FKRoQ1UGrROtjtnrkE0JlLTUKAGW_JASXqA/viewform

**Comment by whit537** [comment]
@jdorfman These three seem like dupes of each other:

- "Additional feedback"
- "Any additional comments regarding the sessions or overall agenda?"
- "Any overall feedback for the event?"

Can we boil down to one?

**Comment by whit537** [comment]
@piamancini on private email thread:

> This is a great next step. I am swamped and traveling again soon, would love to make sure we are handling the data as well. 
Maybe hiring someone to make sense of it?
Any ideas?

**Comment by piamancini** [comment]
@whit537 @jdorfman sorry I wasn't clear, I was talking about the data produced in the conference. I think the survey should be pretty easy to digest.

**Comment by whit537** [comment]
> I was talking about the data produced in the conference.

Ah, sorry. In that case ... noted on https://github.com/sustainers/website/issues/132. :-)

**Comment by jdorfman** [comment]
@whit537 emailing you the form, please keep URL private until it is done.

**Comment by jdorfman** [comment]
Email
**Subject:** Your feedback matters
**Body:**

Hello %name%,

First off, thanks for joining us on Monday, we hope you got a lot out of it as we did. We would love to get your anonymous feedback so we can improve future events. Please fill it out here: %short-url%

We will be releasing data and pictures from the event in the next couple of weeks. Please Follow us on Twitter for any future announcements: https://twitter.com/SustainOSS/

Last but not least, we have a discussion forum on GitHub. Make sure to star it and start conversing with your fellow sustainers: https://github.com/sustainers/discussions/issues

Thanks!

Chad, Justin & Pia

**Comment by jdorfman** [comment]
Update: Th MX DNS records are taking forever to update. While mail won't bounce, we still need to update the gravatar.

**Comment by jdorfman** [comment]
Getting closer

![image](https://user-images.githubusercontent.com/398230/27504933-007b7386-5849-11e7-94c3-0520acbb51f9.png)

**Comment by jdorfman** [comment]
Changed it to `hola@` yolo

![image](https://user-images.githubusercontent.com/398230/27505295-0e6eb84c-5851-11e7-97e7-e858573262df.png)

**Comment by whit537** [comment]
!m @jdorfman

**Comment by jdorfman** [comment]
Getting good feedback. Will review during call
