### ISSUE TITLE
Add UK "Cookie Consent"

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#137]
**Looks like:**
![image](https://user-images.githubusercontent.com/398230/40199222-a7e2be50-59cd-11e8-8e37-91867dd7b29c.png)

**Code:**
```
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#000"
    },
    "button": {
      "background": "transparent",
      "text": "#f1d600",
      "border": "#f1d600"
    }
  },
  "content": {
    "href": "https://sustainoss.org/privacy/"
  }
})});
</script>
```

**Comment by XhmikosR** [comment]
Do you mind if we serve the files ourselves?

**Comment by jdorfman** [comment]
@XhmikosR whatever's easier. It's all Cloudflare in the end.

**Comment by XhmikosR** [comment]
Done, in https://github.com/sustainers/website/commit/221dc5f6cf25b1ddbafd266f5522347e55f5e1a8.

I might need to tweak the implementation later, although everything is async loaded already.
