### ISSUE TITLE
Tweet Carousel 

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#14]
Replace the `#hashtag` area with a Carousel of relevant Tweets.

![image](https://cloud.githubusercontent.com/assets/398230/22486621/12bce3d6-e7bf-11e6-906c-f89fff419f92.png)

* IRL Example: https://cl.ly/0o0M351W2H26 via https://slack.com/pricing/enterprise-grid 

Tweets to include:

* https://twitter.com/browniefed/status/825764697777414145
* https://twitter.com/tjholowaychuk/status/825753076598403072
* https://twitter.com/changelog/status/825378157469560832
* https://twitter.com/rajkumartreads/status/824905425506095105
* https://twitter.com/ericholscher/status/824724818696101888
* https://twitter.com/jdorfman/status/824661518792863744
* https://twitter.com/vmbrasseur/status/821189899751563264

**Comment by jdorfman** [comment]
@XhmikosR thoughts?

**Comment by jdorfman** [comment]
Having second thoughts. It will harm the simplicity and performance.

**Comment by XhmikosR** [comment]
Yeah, it will certainly affect performance.

How did you plan to pull those tweets? In the slack example example they seem to just use Twitter widgets.
We could try loading them after `window.onload`.

Not sure when I'll have time to look into this, but you can share the widgets code and the link to the implementation instructions.

**Comment by jdorfman** [comment]
@XhmikosR leaving it open for now. Need to ponder

**Comment by jdorfman** [comment]
@XhmikosR holy shit that click to copy is cool! Great implementation

**Comment by jdorfman** [comment]
Scraping idea
