### ISSUE TITLE
Need a copy of previous web-site with report permalink

### ISSUE THREAD

**Issue by abitrolly** [sustainers/website#152]
Today I came to reference people to report that was made year ago and could not find it. Now there is a landing site with new event and no trace of work that was being done so far. Hopefully, the sustainers initiative will not turn into event business, because incentive of event business is to earn money from the need of people to discuss thing, and without preserved materials they can discuss the same topic again and again without too much progress.

**Comment by jdorfman** [comment]
Hey @abitrolly!

> Now there is a landing site with new event and no trace of work that was being done so far. 

Here you go: https://sustainoss.org/assets/pdf/SustainOSS-west-2017-report.pdf

> Hopefully, the sustainers initiative will not turn into event business, because incentive of event business is to earn money from the need of people to discuss thing, and without preserved materials they can discuss the same topic again and again without too much progress.

Not at all. We are having an identity crisis that we are working on with Ura Design: https://github.com/uracreative/works/issues/14

please bear with us while we figure this out. It wasn't our intention to make it seem like we are putting everything behind a paywall. 

If you have any other questions please email me directly (or ask here): `jd-at-sustainoss.org`

**Comment by elioqoshi** [comment]
The document is quite inaccessible though so we need to ensure that there are good ways to access it on the new website as well.

**Comment by jdorfman** [comment]
@elioqoshi that's why we hired you =)

**Comment by abitrolly** [comment]
@jdorfman so let's keep it open until document is accessible and requirements for sustainers website are updated to avoid such situations in the future.

**Comment by abitrolly** [comment]
What I propose is to add HTML header that contains links to past events. Links should archived static versions of past web sites.

**Comment by elioqoshi** [comment]
> @elioqoshi that's why we hired you =)

Okay, let's tackle the website next then :D

**Comment by XhmikosR** [comment]
I remember I had suggested we added an Archive page or something similar.

**Comment by jdorfman** [comment]
Link added:
![image 2018-08-07 at 10 05 28 am](https://user-images.githubusercontent.com/398230/43791134-8dba3ed0-9a29-11e8-9603-cf7f70676771.png)

**Comment by jdorfman** [comment]
Another update

![image](https://user-images.githubusercontent.com/398230/44314171-31431000-a3ca-11e8-91ea-e6752257905a.png)

**Comment by jdorfman** [comment]
@XhmikosR I like how GitHub does it https://githubuniverse.com/2017/

Can we just create a dir called `2017` and copy the old site into it?

**Comment by XhmikosR** [comment]
Hmm, I'll need to look into it. Because currently we build everything from the master branch. In order to have that, I think we'd need to build and keep the old website unmodified there. Also, the links need to work in the subfolder, etc.

**Comment by XhmikosR** [comment]
Should be doable as long as I figure out a way to keep the old files there. If we were using a separate branch for gh-pages it would be easy.
