### ISSUE TITLE
Rebrand

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#153]
We recently rebranded: https://demo.identihub.co/sustain#/

### To do:

- [x] #152 
- [x] Replace "SustainUK" with "Sustain Summit"
- [x] Update:
  - [x] Logo (Header and Footer)
  - [x] Colors (css)
  - [x] OG images
  - [x] Favicons
  - [x] Forms
  - [ ] Stickers

**Comment by jdorfman** [comment]
@XhmikosR can you please work with @elioqoshi on implementing the new branding? Either way, ping me on Slack tomorrow.

**Comment by XhmikosR** [comment]
Sure thing, I'll try to talk with @elioqoshi today for the details.
