### ISSUE TITLE
Replace Report button with Get Tickets

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#171]
Selling tickets is now the priority. The question is, do we remove the button/link to the report or just straight up replace it?

![image](https://user-images.githubusercontent.com/398230/45306384-5f9ba300-b4d1-11e8-88fb-ba36511334c0.png)

cc @piamancini @alnermcgunn @BenJam @coderberry

**Comment by elioqoshi** [comment]
My view:

Primary Button is "Get Ticket" in teal background and white color
Secondary (Ghost) Button is "2017 Report"

**Comment by elioqoshi** [comment]
Like this: 
![image](https://user-images.githubusercontent.com/5436686/45310012-6eac4080-b525-11e8-9854-d550a4d839b9.png)

**Comment by jdorfman** [comment]
@XhmikosR need some help with the styling https://github.com/sustainers/website/tree/jdorfman-issue-171

**Comment by XhmikosR** [comment]
Sure, thing, I'll take care of it later today or tomorrow morning (EST)!

**Comment by jdorfman** [comment]
merged by @XhmikosR
