### ISSUE TITLE
[WIP] Update Agenda

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#183]
@XhmikosR there will be a new agenda that @alnermcgunn is working on. I'm leaving Monday and might not be able to update the page. 

- [x] Share agenda doc with @XhmikosR 
- [x] Finish Agenda
- [x] Update `agenda.md` & deploy

**Comment by piamancini** [comment]
@XhmikosR 
Clean Agenda 
 https://docs.google.com/document/d/1REQa-t4w1M3gTidoexAGece7zXoXDbKldP23GwTMlPE/edit

**Comment by jdorfman** [comment]
@XhmikosR agenda === schedule

**Comment by XhmikosR** [comment]
Hehe, on it.

**Comment by XhmikosR** [comment]
So, wait, the doc isn't a table anymore. Any suggestions how you want it to show?

**Comment by XhmikosR** [comment]
All right, I'll wait for feedback until tomorrow morning (my time), otherwise I'll go ahead and add it the best way I can without any mockups

**Comment by jdorfman** [comment]
Have it show at bullets like in the doc please
