### ISSUE TITLE
Discourse Tasks

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#187]
### Prelaunch
- [x] [Enable GitHub Login](https://meta.discourse.org/t/configuring-github-login-for-discourse/13745)
- [x] Enable Twitter Login
- [x] Enable Google Login
- [x] Enable "Reply by email"
- [x] Enable CodeFund ads, dump revenue in SustainOSS collective cc @coderberry

**Comment by jdorfman** [comment]
GitHub is done
![image](https://user-images.githubusercontent.com/398230/48780152-119fda00-ec8e-11e8-8797-c32f7739b1e6.png)

@XhmikosR can you test it please?

**Comment by jdorfman** [comment]
![image](https://user-images.githubusercontent.com/398230/48780205-3e53f180-ec8e-11e8-9dcc-57896ed96522.png)

Twitter is going to take a few days. @coderberry @XhmikosR @BenJam do you have a Twitter Developer account we can use for the OAuth?

**Comment by jdorfman** [comment]
Google enabled 

![image](https://user-images.githubusercontent.com/398230/48781244-82e08c80-ec90-11e8-8ff0-f8c1d24fc615.png)

**Comment by XhmikosR** [comment]
Sorry, I don't have a Twitter dev account either :/

**Comment by jdorfman** [comment]
Twitter is GTG

**Comment by jdorfman** [comment]
@erlend-sh can you help with the "reply by email" Discourse feature?

**Comment by erlend-sh** [comment]
Since you’re hosted with us it should just be a matter of enabling the setting.

**Comment by XhmikosR** [comment]
@erlend-sh: do you happen to have a nice SVG we could use? Currently we are using feather icons but they don't have a Discourse icon.

**Comment by jdorfman** [comment]
Google Update

![image](https://user-images.githubusercontent.com/398230/48853716-f8b62800-ed64-11e8-8e16-02572f9fd992.png)

**Verified & Responded**
```
> dig sustainoss.org txt

;; ANSWER SECTION:
sustainoss.org.		300	IN	TXT	"google-site-verification=dVcOQ6ivGNOZZFeRZ1rkdG4v-CNFZdD-3Jwd_Sn4ruk"
sustainoss.org.		300	IN	TXT	"v=spf1 include:mailgun.org ~all"
```

**Comment by jdorfman** [comment]
Reply by email GTG thanks @erlend-sh 

![image](https://user-images.githubusercontent.com/398230/48854295-6878e280-ed66-11e8-9ef0-5f21723994f0.png)

**Comment by abitrolly** [comment]
Is that a self-hosted instance?

**Comment by jdorfman** [comment]
@abitrolly no they are graciously hosting it for us.
