### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#188]
Dedicated page for hosting pictures from 2018 Summit (eventually 2017)

via @xhmikosr 

```
just thumbs which we'll create once, and baguettebox, and lazy loading for the thumbs if needed"

I was thinking like 4 in a row
we'll figure out the math when we get to it
we could even add https://isotope.metafizzy.co/
```

**Comment by jdorfman** [comment]
@elioqoshi do you want to design this or can we take a stab?

**Comment by elioqoshi** [comment]
@jdorfman how about if you take a stab and I have a look afterwards to do another iteration? We should prioritize moving quick rather than being perfectionists at this point I assume
