### ISSUE TITLE
Post Summit Design Tasks

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#192]
- [x] Design Feather-esk icon for [Discourse](https://commons.wikimedia.org/wiki/File:Discourse_icon.svg)
- [x] Link in footer next to Twitter icon
![image](https://user-images.githubusercontent.com/398230/48639602-e7e26c80-e988-11e8-838c-5ed9fc79106f.png)
- [x] Redo hero image for mobile

**Comment by jdorfman** [comment]
![image](https://user-images.githubusercontent.com/398230/48855076-3cf6f780-ed68-11e8-9abe-8d7cf2a52954.png)

**Comment by elioqoshi** [comment]
The image for mobile should be cropped with css (scale the image to the height of the block) rather than change the image I'd suggest

**Comment by jdorfman** [comment]
@XhmikosR ^

**Comment by XhmikosR** [comment]
A shitty image will look shitty. Just fix the small image.

**Comment by XhmikosR** [comment]
The height I will fix it tomorrow.

**Comment by jdorfman** [comment]
Looks weird on iOS/Safari

![image](https://user-images.githubusercontent.com/398230/48955073-07394680-ef01-11e8-93af-bb94cf0d060e.png)

**Comment by XhmikosR** [comment]
What iPhone version is that? Because it was always like that if it's an iPhone 5.

**Comment by jdorfman** [comment]
@XhmikosR lol yeah it was my mom's `5`
