### ISSUE TITLE
Post launch Discourse tasks

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#195]
via @elioqoshi 

Todo:
- [x] Updated a few colors to be compliant with branding
- [x] I'd suggest Sustain Forum not SustainOSS Forum
- [x] I'd suggest also offering a category view instead of only latest
- [ ] there are also way too many categories. Let's talk to clean up a bit, we don't want any category to die down

**Comment by jdorfman** [comment]
@elioqoshi what categories should go? cc @coderberry

**Comment by jdorfman** [comment]
@elioqoshi we offer Category & Latest. 

![image](https://user-images.githubusercontent.com/398230/49166475-480dd280-f2e8-11e8-9436-85c9b6866f3f.png)

**Comment by abitrolly** [comment]
How this Discourse is instance is hosted and maintained (backups etc.)? I think about deploying it for local hackers community, but I am not sure I have the time to maintain it.

**Comment by jdorfman** [comment]
@abitrolly hosted
