### ISSUE TITLE
Design Media Page

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#199]
for #197 

Chat with @anxh3l0 

```
Probably tabs would be a good idea
Since long vertical pages are not good UX wise
```

**Categories/tabs:**
* Photos
- [x] Videos
    - * `https://youtu.be/713I5bhVdIc` (remove last frame if possible https://cl.ly/63d82bd5b1b0)

- [x] Reports
    * https://sustainoss.org/2017-report/ (use page 1 of pdf as thumbnail, don't mention 2018 yet)

* Podcasts
* Articles

- [x] Article links

    * [Is open source wealth distribution fair?](https://opensource.com/article/18/12/wealth-open-source-distributed) - by Georg Link
    * [#SustainOSS 2018 Notes](https://medium.com/@lpnotes/sustainoss-2018-notes-d679dd9785ca) - by Linda Peng
    * Got one? [Share it in the Forum](https://sustainoss.org/forum/)

**Comment by jdorfman** [comment]
**Initial mockup:**
![image](https://user-images.githubusercontent.com/398230/49296747-f7c07d00-f46d-11e8-9413-e22130d4e2b2.png)

**Scaffold**
![image 2018-12-06 at 11 27 16 am](https://user-images.githubusercontent.com/398230/49609242-c48b5b80-f94f-11e8-8d32-2694f78609d7.png)

**Comment by jdorfman** [comment]
- [ ] Article links

* https://opensource.com/article/18/12/wealth-open-source-distributed
* https://medium.com/@lpnotes/sustainoss-2018-notes-d679dd9785ca
* "Got one? Share it on the Forum"

**Comment by jdorfman** [comment]
- [ ] Video: `https://youtu.be/713I5bhVdIc`

- [ ] Reports: https://sustainoss.org/2017-report/ (use page 1 of pdf as thumbnail)

**Comment by jdorfman** [comment]
video: https://www.youtube.com/watch?v=LxanTEHo6BQ

Channel: https://www.youtube.com/channel/UCH7TBTJ12JFaIwfK-0QKClQ

**Comment by XhmikosR** [comment]
It doesn't seem to be any longer possible to remove the related videos at the end, at least not completely. It might be possible to choose the related videos you want to show on YouTube though.

I finished the tabs. For the photos I will show two thumbs, each one will go to a separate page for each gallery.

**Comment by jdorfman** [comment]
@XhmikosR good call

I added an "End Screen", still processing

**Comment by jdorfman** [comment]
@XhmikosR Report thumbnails: https://cl.ly/c2038e7cbe28
