### ISSUE TITLE
Design 2018 report cover

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#206]
For @AnXh3L0 

The 2018 report is being worked on. We need a cover page (8.5x11" 300dpi). This was last years https://sustainoss.org/2017-report/

Can't wait to see what you come up with.

**Comment by elioqoshi** [comment]
@jdorfman I don't think a cover is enough for this. Let's make the whole report publishing layout. Once you have the report document ready, send it to us for publishing. Please consider a timeline of at least 1 week from start to finish of the design.

**Comment by jdorfman** [comment]
Good call, will do.
