### ISSUE TITLE
Error: Submitted URL marked ‘noindex’

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#212]
Not sure if this is by design? Via [search.google.com](https://search.google.com/search-console/index/drilldown?resource_id=https%3A%2F%2Fsustainoss.org%2F&item_key=CAMYHCAE&utm_source=wnc_10030322&utm_medium=gamma&utm_campaign=wnc_10030322&utm_content=msg_100058679&hl=en&sharing_key=pq5QWqgPC8ym1_EEyKR6xA)

![image](https://user-images.githubusercontent.com/398230/50461558-16fadf00-0934-11e9-8464-5dc0ee4b5a88.png)

**Comment by XhmikosR** [comment]
That's fine, those are redirects.
