### ISSUE TITLE
Sponsorship Form

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#225]
We added 2 buttons in #224 

@piamancini had great feedback "Should we create a sponsorship form or at least button with a mail to"

Google Forms might be the best way to go to keep the data secure and centralized.

Fields:
```
Name
Email
Company
Message
```

Link or Button?

<img width="627" alt="Image 2019-10-02 at 4 07 56 PM" src="https://user-images.githubusercontent.com/398230/66088194-1d576080-e52f-11e9-88c7-190497630559.png">

**Comment by piamancini** [comment]
I can create a new event on the sustain collective and we can direct sponsors there. 
I would also add a link for contact - maybe they want to discuss sponsorship options or give us something in kind for example.

**Comment by jdorfman** [comment]
Yeah let's get the event up and we can just link to that.

I'll just link to hola@ for now.

**Comment by piamancini** [comment]
I'm blocked on creating the event because we screwed something up in events with the new collective page. I need to work on it. In the meantime I created a new stand-alone tier for Sustain, you can link to it. https://opencollective.com/sustainoss/contribute/sustain-2020-brussels-11769
