### ISSUE TITLE
Add 2020 events to the Events page

### ISSUE THREAD

**Issue by RichardLitt** [sustainers/website#235]

**Comment by abitrolly** [comment]
What is the reason to close this? No events?

**Comment by RichardLitt** [comment]
Good question! All of the events are on the page. https://sustainoss.org/events/

Am I missing something?

**Comment by abitrolly** [comment]
@RichardLitt look like the report from `Sustain Summit 2020` is missing.

![image](https://user-images.githubusercontent.com/8781107/101396192-030bd600-38dc-11eb-8786-4e1eba8c7158.png)

**Comment by jdorfman** [comment]
@abitrolly It's coming, final touches are being applied.

**Comment by abitrolly** [comment]
@jdorfman keep this issue open until then?

**Comment by RichardLitt** [comment]
It's not quite the same. I'll open a new issue, if you feel it's necessary? Don't worry, we'll post the report here. :)

**Comment by abitrolly** [comment]
I am not that eager to see the report to open a new issue. It bothers me that like with current issue it is not clear what's going on on this public tracker. It might be quite uncommon for corporates to close issues without a commit reference (and I am talking about  https://github.com/epam/OSCI) or use parallel processes, so nothing is visible to outside contributors. I count this as an anti-pattern for keeping people up to date and involved with the project.

On the second thought I still want to read the report. )

**Comment by RichardLitt** [comment]
To be honest, I didn't think anyone watched this website for updates. Now that I know that, I will include more details when I close things. Thanks for watching and commenting!
