### ISSUE TITLE
Add podcast to the website

### ISSUE THREAD

**Issue by RichardLitt** [sustainers/website#236]

**Comment by RichardLitt** [comment]
One thing which we need to do is to adjust the Media page to not have the old CHangelog podcasts, or to move them down somewhere and to highlght the current podcasts.

**Comment by jdorfman** [comment]
I agree. For now Fireside is fine, but definitely want to get the content (show notes) on our domain.

**Comment by jdorfman** [comment]
I'm testing this out to see if it sparks any conversations

https://discourse.sustainoss.org/c/podcasts/18

**Comment by RichardLitt** [comment]
This can be closed. We link to it in the header.
