### ISSUE TITLE
Fix GitHub Actions breaking on `bundle exec jekyll build`

### ISSUE THREAD

**Issue by RichardLitt** [sustainers/website#249]
I'm debating just moving off of GitHub pages entirely. Right now, I have to force rebuild until it works, and even then, I've had issues where the site hasn't updated on merge or on commit push that does pass. 

Can we switch to Netlify? I don't recall them having this problem. Otherwise, can we get rid of the ffi package? 

@XhmikosR Any idea why we're getting this error with this build, at the moment? I'm not getting it on any of my other sites.

**Comment by jdorfman** [comment]
@RichardLitt we are using Netlify.

![image](https://user-images.githubusercontent.com/398230/77723239-22acd980-6fad-11ea-82d5-1b2d8e411657.png)

**Comment by RichardLitt** [comment]
Well I'm going to bed. I make stupid mistakes when I'm tired.

**Comment by XhmikosR** [comment]
The problem is probably Cloudflare caching. We can just add a GitHub Action to purge the cache.

**Comment by XhmikosR** [comment]
Nevermind the above comment, @RichardLitt needed sleep, I need more coffee 😁

The `bundle exec jekyll build` issue is **unrelated** to the above. It's related to a bug somewhere in one of the gems. I've hit this in the past with Netlify too, so it might not be fixed 100% with switching to Netlify. And we need some way to test things, which is were the issue happens. I'll check and see if there are any dep updates soon.

**Comment by XhmikosR** [comment]
Things seem to work fine after the recent patches I pushed. The issue might still occur, but restarting CI should fix it. The issue will be completely fixed if the gems are fixed (I think it's the sassc gem), so it might be worth checking for gem updates in the near future.

Feel free to close the issue.

**Comment by RichardLitt** [comment]
Ok. Thank you, @XhmikosR! Will reopen if needed.

**Comment by jdorfman** [comment]
@RichardLitt I moved back to GitHub Pages per @XhmikosR's request. I also purged the Cloudflare cache.
