### ISSUE TITLE
Webmaster tools

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#25]
re-setup webmaster tools on Google

- [x] Add all your website versions
- [x] Select your preferred version
- [x] Select target country
- [x] Share access with co-workers
- [x] Associated Analytics web property
- [x] Submit a sitemap file

**Comment by jdorfman** [comment]
@XhmikosR how did you create the sitemap? Or could you just regenerate it for the new domain?

**Comment by XhmikosR** [comment]
The sitemap is automatically generated on build.

**Comment by XhmikosR** [comment]
Let me have a look. You missed some stuff.

**Comment by XhmikosR** [comment]
What's the twitter url? The same as before?

**Comment by jdorfman** [comment]
@XhmikosR https://twitter.com/SustainOSS

**Comment by XhmikosR** [comment]
Done in master. Just resubmit the sitemap and close this.

**Comment by jdorfman** [comment]
It is adding `www` e.g. https://www.sustainoss.org/sponsor/, is that ok? It redirects but could be confusing.

**Comment by XhmikosR** [comment]
I thought you kept the same scheme.

Of course it should be consistent so I'll change it.

**Comment by XhmikosR** [comment]
Done.

**Comment by jdorfman** [comment]
Thanks!
