### ISSUE TITLE
Add more to docs group and act up tasks

### ISSUE THREAD

**Issue by ChrisChinchilla** [sustainers/website#265]

**Comment by ChrisChinchilla** [comment]
@RichardLitt Can you assign me? I don't have permission to do so.

**Comment by RichardLitt** [comment]
Invited you with Triage permissions.

**Comment by ChrisChinchilla** [comment]
Hmm, that still doesn't seem to be enough, which seems odd…

**Comment by RichardLitt** [comment]
That does seem odd. Maybe you can't assign under triage. Will up your admin privs.
