### ISSUE TITLE
New Coverage issues detected

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#269]
## Google Search Console

**Submitted URL marked ‘noindex’**

```
https://sustainoss.org/about/ | Mar 22, 2020
https://sustainoss.org/diversity/ | Feb 27, 2020
https://sustainoss.org/contact/ | Jan 17, 2020
https://sustainoss.org/events/ | Dec 29, 2019
```

**Submitted URL blocked by robots.txt**

```
https://sustainoss.org/working-groups/governance-readiness/ | Mar 27, 2020
```

**Comment by RichardLitt** [comment]
@jdorfman I can't verify DNS as I don't own the domain. Could you? https://search.google.com/search-console/welcome

**Comment by jdorfman** [comment]
Better yet, I will use this as an opportunity to decentralized our DNS and Domain management.

I still "own" `sustainoss.org` which should be transferred to the Open Source Collective IMO.

I'll talk to Alana about that.

**Comment by XhmikosR** [comment]
I'd say just ignore these; many times Google throws this kind of errors.
