### ISSUE TITLE
Book a venue (or change date?)

### ISSUE THREAD

**Issue by whit537** [sustainers/website#27]
GitHub is not available during May due to construction.

Microsoft's public space is also under construction in the spring.

Other options?

**Comment by whit537** [comment]
I made a [connection](https://twitter.com/whit537/status/829074309712855040) with Amazon and have followed up in email.

**Comment by whit537** [comment]
Given that GitHub is willing to pay for space (ya?), another option:

http://sanfrancisco.impacthub.net/rent-our-space/
http://oakland.impacthub.net/booking/

**Comment by jdorfman** [comment]
@whit537 what did Amazon say? I love the AWS Loft, great thinking.

re: GitHub I rather try to get a venue in-kind and put that money towards lunch or whatever else.

**Comment by whit537** [comment]
@jdorfman No word since the other day. Here's the email exchange we had:

>> Thanks for the response on Twitter. Short story is that we're putting together a one-day event for about 75 people involved in open-source sustainability: https://sustainoss.org/.
>>
>>We just found out that GitHub can't host after all, nor can Microsoft. We're casting about for options and thought the Amazon Loft might be a possibility? We were looking at May 24, could fudge a little bit.
>>
>>Thanks for any leads! We'd love to have Amazon involved one way or another. :-)

-------------------

> Let me see what I can do….

----------------------

>> Thanks so much, Jeff! :D

**Comment by jdorfman** [comment]
I can reach out to my contact(s) at Mozilla but I want to make sure we are not going with someone else first.

**Comment by whit537** [comment]
@substack's [latest](https://twitter.com/jashkenas/status/829817619410780160) reminds me: we could also go for Sudo Room/Omni Commons if we wanted a less corporate/more DIY feel?

![layout1](https://cloud.githubusercontent.com/assets/134455/22822454/98915718-ef4d-11e6-9c11-04d48caf4248.jpg)

http://oaklandlocal.com/2014/11/oaklands-omni-commons/

**Comment by bkeepers** [comment]
Hey, I've been chatting with @piamancini via email, but will just chat here instead 😁 

Sorry about having to move due to construction in GitHub's office. We'll sponsor whatever is needed to make this event happen. The GitHub office is currently available on most Mondays/Wednesdays starting in June if any of those dates work for anyone.

**Comment by gr2m** [comment]
I’m okay with moving this to June from my side, I don’t know if there are already folks who said that is not the preferable option

**Comment by whit537** [comment]
No word back from Amazon.

I'd be fine with GitHub in June, but Gunner is available on June 8 or 9 iirc, neither of which is a Monday or Wednesday.

**Comment by piamancini** [comment]
@bkeepers thanks! if we move to June, it'd have to be 8th or 9th. is that an option?

**Comment by whit537** [comment]
Pinged Jeff at Amazon:

> Any word on this? Who would be the best person to talk to about booking the space?

**Comment by bkeepers** [comment]
> @bkeepers thanks! if we move to June, it'd have to be 8th or 9th. is that an option?

Sorry, only Mondays and Wednesdays 😢

**Comment by jdorfman** [comment]
July?

**Comment by piamancini** [comment]
let me see what other dates gunner has available on june

**Comment by piamancini** [comment]
From Gunner: As of now, the weeks of 12 June and 19 June are open. @bkeepers @jdorfman @whit537 @gr2m @andrew any preferences on your end between 12th, 14th or 19th, 21st?

**Comment by whit537** [comment]
| | date |
|----|------|
| 👍 | June 12 |
| 😄 | June 14 |
| 🎉  | June 19 |
| ❤️  | June 21 |

**Comment by jdorfman** [comment]
@piamancini sorry just saw this. Setting up better notifications.

**Comment by gr2m** [comment]
all work so far

**Comment by BenJam** [comment]
Dates are all good for me. We're keen to be a part of this so assume we'll work around it.

**Comment by bkeepers** [comment]
GitHub HQ is currently available **June 14** and **19**.

**Comment by whit537** [comment]
@jdorfman and I are disjoint on the two weeks, he preferring the latter. I can make the 19th work if that's the consensus.

**Comment by jdorfman** [comment]
To be completely transparent, I have a company retreat `May 29 to June 2`.

The backup dates are:
* June 5 to 9
* June 12 to 16

99.99% chance it will be `May 29 to June 2` but don't want to risk it.

**Comment by whit537** [comment]
June 19 is the first week of summer vacation for my kids, so it'd be neater for me if I was gone the week prior, but not a huge deal. :-)

**Comment by jdorfman** [comment]
@whit537 field trip =)

**Comment by whit537** [comment]
We _were_ thinking of taking a roadtrip this summer, but that was a little earlier than we were thinking. ☺️

**Comment by whit537** [comment]
@piamancini in slack:

> let me reconnect with the thread. but it looks good to me

**Comment by whit537** [comment]
So what's the decision here, @jdorfman? You ready to lock in the 19th w/ Gunner and GitHub?

**Comment by jdorfman** [comment]
shit sorry yeah the 19th. Who else are we waiting on?

**Comment by whit537** [comment]
Looks like the 19th isn't ideal for @pzwang, but the neither is the 14th. 😞

Might double-check with @piamancini but it sounds like she's good. And anyway she's the one to lock this in with Gunner.

I think we're ready to make a decision, @jdorfman. Your call!

**Comment by whit537** [comment]
@jdorfman PR in https://github.com/sustainers/website/pull/35 when you're ready. 🙇

**Comment by piamancini** [comment]
I'm cool with any dates. What's the date to lock in with Gunner then, the 19th?

**Comment by whit537** [comment]
@piamancini in Slack:

> gunner is locked in for the 19th

💃

@bkeepers We are ready to lock in the 19th! Is that date still good?

**Comment by bkeepers** [comment]
Yes. I just put in the request to reserve it! 🎉 

cc @nayafia

**Comment by whit537** [comment]
Woo-hoo! Thanks @bkeepers. :)

@jdorfman I believe #35 is yours to merge. :)

**Comment by whit537** [comment]
Follow-up to Jeff:

> Quick heads up that we've now booked GitHub in June. Would still love to have Amazon participate. Get in touch if interested! Have a great day! :-)

**Comment by whit537** [comment]
Jeff:

> We can’t help out this time, but please check back again prior to your next event.

**Comment by jdorfman** [comment]
meh. All good.
