### ISSUE TITLE
Update 'Become a supporter' copy

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#28]
Replace `unconference` & `#sustainunconf` via: https://opencollective.com/sustainoss#support 

![image](https://cloud.githubusercontent.com/assets/398230/22767342/86253456-ee2f-11e6-8488-d895721a4c8c.png)

**Comment by jdorfman** [comment]
@piamancini I was unable to update it using my account. Is it a backend thing?

**Comment by piamancini** [comment]
@jdorfman yep. I'll do it
