### ISSUE TITLE
Confirmation email copy for donation

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#29]
via @piamancini 

* also, we need to come up with a confirmation email wording for when someone makes a donation
* so far they don't know they are confirmed
* if you can draft something, I can edit the open collective template on the back end

**Comment by jdorfman** [comment]
Hello {{name}},

Thanks so much for being part of the first $ustainOSS Conversation! We look forward to meeting you on {{date}} at {{venue}}.

Next steps:
* Follow us on Twitter: {{twitter_url}}
* Join us on GitHub: {{github_url}}
* Talk with us on Slack: {{slack_info}}

**Comment by piamancini** [comment]
on it

**Comment by piamancini** [comment]
merged: https://github.com/OpenCollective/opencollective-api/pull/791
