### ISSUE TITLE
Dependabot Alert

### ISSUE THREAD

**Issue by chimosky** [sustainers/website#293]
@RichardLitt would you take care of the dependabot alert although it's of low-severity.

**Comment by RichardLitt** [comment]
I'm not seeing the alert. Where are you seeing it?

**Comment by chimosky** [comment]
Saw one earlier today in the [Security](https://github.com/sustainers/website/security/dependabot) page and got a dependabot alert earlier.

**Comment by RichardLitt** [comment]
Cool. I renamed `master` to `main`, and it appears to have fixed it. 🤔

**Comment by chimosky** [comment]
Yeah I noticed that, it might probably appear after a while.
