### ISSUE TITLE
Add Gunner's bio

### ISSUE THREAD

**Issue by whit537** [sustainers/website#30]
Gunner is going to be a key player in this event. We should front-load that on the website and explain who he is and why we picked him to help us here.

Also, is he on GitHub? Feels weird to keep talking about him behind his back. ;-)

**Comment by jdorfman** [comment]
@whit537 great point. He should be on the home page IMO.

**Comment by whit537** [comment]
@piamancini You are in contact with him, yes? Can you get this info? Or do we have a link to a page of his somewhere we can take this from?

**Comment by whit537** [comment]
https://aspirationtech.org/about/people/gunner

**Comment by whit537** [comment]
(Shared in Slack.)

**Comment by piamancini** [comment]
![aspiration_logo300](https://cloud.githubusercontent.com/assets/3671070/24157823/e3857568-0e30-11e7-814a-7bc18157834d.jpg)

**Comment by whit537** [comment]
https://aspirationtech.org/ is 500 right now.

**Comment by jdorfman** [comment]
Getting the same response too

**Comment by jdorfman** [comment]
I think we need to just rehaul the about page.

* Who's involved
* About Gunner and Aspiration
* etc

**Comment by whit537** [comment]
PR in #52.

**Comment by whit537** [comment]
Closing per (private) call w/ Gunner.
