### ISSUE TITLE
Put together sponsorship prospectus

### ISSUE THREAD

**Issue by whit537** [sustainers/website#31]
I believe Sauce Labs asked @piamancini for this.

**Comment by jdorfman** [comment]
Some good templates:

* https://docs.google.com/document/d/17ksd6K3ijUe0h8Iuou993qLfYnyWSw4ffob8XdIjhSE/edit
* https://us.pycon.org/2017/sponsors/prospectus/
* https://2017.midwestphp.org/prospectus.html

**Comment by whit537** [comment]
@jdorfman sez (on standup call) that we should block this on a schedule/agenda (#9?) so we know what we have to offer.

**Comment by whit537** [comment]
Per @piamancini on (private) weekly call: Our main cost is the facilitator (#30), minimum $5,000, better would be $10,000 to $20,000.

**Comment by whit537** [comment]
Scholarship fund (#32) would be overflow.

**Comment by whit537** [comment]
@jdorfman on (private) weekly call:

$500 gets you:

- 2 passes
- logo/link on website
- $25 credit for sticker swap table

**Comment by whit537** [comment]
I believe there's a private Google Doc where we're tracking this.

**Comment by whit537** [comment]
Closing per @jdorfman, he's having good enough luck w/ personal outreach, doesn't feel the need for a prospectus.
