### ISSUE TITLE
Set up a travel assistance fund

### ISSUE THREAD

**Issue by whit537** [sustainers/website#32]
If we get enough sponsorship (#31) then we could consider a scholarship fund.

**Comment by jdorfman** [comment]
@whit537 how would this work?

**Comment by whit537** [comment]
We'd set aside funds for the purpose, and then folks like @fijal could/would apply for travel assistance.

**Comment by jdorfman** [comment]
Ah, got it. I thought you meant putting someone through school.

**Comment by whit537** [comment]
The School of Sustaining OSS!

**Comment by whit537** [comment]
There was discussion on today's (private) call about how to prioritize this. If we don't have any poor maintainers at the conf then we're missing half the people we need in this conversation. On the other hand fundraising (#31) is going to be tough for a small event and we also want to keep the budget way down to shoestring levels. No definite conclusiosn.

**Comment by piamancini** [comment]
This is the ticket for the travel fund https://opencollective.com/sustainoss/events/2017

**Comment by whit537** [comment]
Bringing over from https://github.com/sustainers/website/issues/69:

> @BenJam has been talking to Sloan for travel support. The process might be that we need to make a formal application to support XX tix for XX participants. A way of managing that is to add a google form on the website for people to apply for assistance with travel details.

**Comment by BenJam** [comment]
I've (quietly) been on holiday the last two weeks but I'm back now. I'll find out a little more about the process. I take it the form hasn't been added yet so I'll do that ASAP.

**Comment by whit537** [comment]
Word from @piamancini on (private) weekly call is that there may be an organization willing to help with this.

**Comment by whit537** [comment]
@BenJam Bump. Where do we stand on this?

**Comment by BenJam** [comment]
Thanks for the bump @whit537 I'll get back on it.

**Comment by whit537** [comment]
Invite sent! In the mean time, it seems I can't assign to a non-org-member ...

**Comment by whit537** [comment]
From @BenJam in Slack:

> I need to add some more detail on []’s travel fund but if we ask openly what people’s expected cost will be for travel and accomodation I’m sure that would be enough to build a case for them to approve.

**Comment by whit537** [comment]
Weekly private call: need to write a grant for this. Who is the receiving organization? @alnermcgunn offers Aspiration! @alnermcgunn and @BenJam to coordinate.

**Comment by whit537** [comment]
Per private weekly call earlier today: @BenJam intends to set up a Google Form to collect applications from interested people. This will feed into the grant application.

**Comment by BenJam** [comment]
Google form https://docs.google.com/forms/d/1ZVq3ksNtTKUwoG-JWpk0geMjg15v1l2S-Vofi3tER0I/edit

Feedback welcomed.

**Comment by whit537** [comment]
> We will notify you of approval by Friday 26th May 2017. 

Tight timeline! We'd better start #56'ing. 😳

**Comment by whit537** [comment]
"Option 4"?

**Comment by BenJam** [comment]
> "Option 4"?

what? you don't like good option 4? ;)

Ta, will remove.

**Comment by whit537** [comment]
We're live: https://sustainoss.org/travel-support/.

LF has also offered to contribute.

**Comment by whit537** [comment]
Awesome work, @BenJam. Thank you! 👍
