### ISSUE TITLE
Move Slack to Changelog

### ISSUE THREAD

**Issue by whit537** [sustainers/website#33]
What would you all think of moving the Slack channel from OpenCollective to Changelog? Seems like a good hook to get Changelog more involved with $ustain, and it aligns well with their purpose and role in the wider community.

cc: @adamstac @jerodsanto

**Comment by jerodsanto** [comment]
SGTM

**Comment by adamstac** [comment]
Let's do it!

**Comment by whit537** [comment]
PR in https://github.com/sustainers/website/pull/34 ...

**Comment by piamancini** [comment]
can you share the new slack?

**Comment by whit537** [comment]
Join via https://changelog.com/community, #sustain channel.

See yinz over there! 💃
