### ISSUE TITLE
Write a blog post about the telescope

### ISSUE THREAD

**Issue by Anita-ihuman** [sustainers/website#340]
Write a blog post on OSS comes to play in the Mikulski Archive for Space Telescopes (MAST) archives. 

Reference 
- [Podcast](https://t.co/I8SE6spZuP)

**Comment by Anita-ihuman** [comment]
Here is a draft of this blog post.
Please review and leave a comment

https://docs.google.com/document/d/1Kbmsn67DXCq0HfFVnQ_B3xVhUV2iLCQ5TzSu4xpi6xE/edit?pli=1#

**Comment by abbycabs** [comment]
Thanks for putting this together @Anita-ihuman! I can't seem to open the first link?

**Comment by abbycabs** [comment]
Hi @Anita-ihuman! You can make a blog post by adding a file here: https://github.com/sustainers/website/tree/main/_posts

**Comment by Anita-ihuman** [comment]
@abbycabs @Victorybrown I was able to record this file, and it's available now. I will go ahead and create a PR once the review is confirmed. 
- [Open Source Influencing Space Programs: JWST](https://docs.google.com/document/d/1Kbmsn67DXCq0HfFVnQ_B3xVhUV2iLCQ5TzSu4xpi6xE/edit?pli=1#)

**Comment by Victorybrown** [comment]
This looks good! Great work Anita.

**Comment by RichardLitt** [comment]
\o/
