### ISSUE TITLE
Invite me to awesome Sustainers Community.

### ISSUE THREAD

**Issue by DevStar0202** [sustainers/website#346]
Hello dear.
Please invite me to your group.
------------------------------------About me--------------------------------------------------------------
Hope you’re doing well.
I’d like to make you an offer and some background so you can check my work out.
From the beginning you can get acquainted with some Node.js based websites developed by me
- https://eltoftnielsen.dk/
- https://pfefferundfrost.de/
- https://www.harcome.com/
Check some react based projects done by me
- https://www.codecademy.com/
- https://www.grammarly.com/
And my other works
- https://goldlingdrinks.com/
- https://tropicalmoscato.com/
- https://en.wearenoodz.com/
- https://app.wookmama.co/
Providing my skills, I would like to mention the following:
- HTML5/CSS3
- JavaScript: Node.js, Angular.js, React.js, Vue.js
- CMS: WordPress, OpenCart, Magento, PrestaShop, Shopify, Drupal, Wix
- Responsive Web Development, Twitter BootStrap, Restful V.eb Services
- Python, Objective - C (iOS), Java, Flutter
- GitHub and Agile dev methodologies
- React Native
- SEO
- Ajax, JQuery, SaaS, APIS, 3rd party APIS
- DB: mySQL, SQL, MongoDB
- -------------------------------------------------------------------------------------------------------

Thanks. Daivid

**Comment by RichardLitt** [comment]
Hey Daivid,

I'm not sure what you mean by please invite me to your group. You're free to come and join us on discourse.sustainoss.org.
