### ISSUE TITLE
Create a mailing list for email notifications

### ISSUE THREAD

**Issue by danielbachhuber** [sustainers/website#37]
It would be helpful to have an input field where I could put my email address and receive notifications of updates.

**Comment by whit537** [comment]
Sounds good to me. Any interest in helping set this up, @danielbachhuber? :-)

**Comment by danielbachhuber** [comment]
I'd suggest using [TinyLetter](http://tinyletter.com/). Pretty easy to sign up and link to the subscription form.

**Comment by whit537** [comment]
Personally I do use email as a way to stay informed about things I care about, so I agree that setting up an email list would be beneficial for us. However, we would need someone to step forward to own this in order for it to happen.

@danielbachhuber Do you have any time/interest in running this for us? We have weekly standup calls on Tuesdays at 9 am US/Pacific and an active Slack channel (#sustain on [the Changelog slack](https://changelog.com/community)). That'd be the best way to coordinate with the rest of the group on sending out significant news. Up for it? :-)

**Comment by danielbachhuber** [comment]
I don't, sorry.

**Comment by whit537** [comment]
Okay. :-)

**Comment by RichardLitt** [comment]
I should have time to do this. I'll attend the next meeting and let you know then.

**Comment by whit537** [comment]
Talking on (private) weekly call w/ @jdorfman @RichardLitt, plan is:

- newsletter with MailChimp
- signup on website
- mail every other 
- what should we use as a from address? what@sustainoss.org? infra for this?

**Comment by whit537** [comment]
@jdorfman controls DNS for the domain, will coordinate MX change as necessary.

**Comment by RichardLitt** [comment]
- [x] Set up tinyletter
- [x] Send test email
- [ ] Get sustainoss.org email
- [ ] Add to website
- [ ] Draft initial newsletter

**Comment by jdorfman** [comment]
@RichardLitt where are you thinking of placing the form?

**Comment by jdorfman** [comment]
Draft initial newsletter should be another tasks
