### ISSUE TITLE
Pay Gunner

### ISSUE THREAD

**Issue by whit537** [sustainers/website#38]

**Comment by whit537** [comment]
Per (private) weekly call: @piamancini to finalize a fee, perhaps before our next call.

**Comment by whit537** [comment]
@piamancini talked to @alnermcgunn and we are locked in at $5k. 👍

**Comment by jdorfman** [comment]
Can we close this?

**Comment by whit537** [comment]
Oh, probably. Pretty sure GitHub is good for the cash. ;-)
