### ISSUE TITLE
Sort out food

### ISSUE THREAD

**Issue by whit537** [sustainers/website#39]
@piamancini suggests on (private) weekly call that food is easier for companies to handle as gift-in-kind vs. money (budget, #31) per se.

**Comment by whit537** [comment]
@adamstac suggests partnering w/ local restaurants/food trucks and sending people out for lunch.

**Comment by bkeepers** [comment]
Hey @whit537, I was actually expecting that GitHub would just cover catered breakfast, lunch, and happy hour.

Do you mind if one of us from GitHub start joining these planning calls? We'd love to help as much as we can.

**Comment by piamancini** [comment]
hi @bkeepers That would be great!  Please you are welcome to join the calls. They are Tuesdays @ 9am PT. We are also now on the Changelog Slack. channel #sustain

**Comment by whit537** [comment]
Thanks @bkeepers. Will you need more input from us? If so let's keep this ticket open, if not we can close.

**Comment by jdorfman** [comment]
I ❤️  @bkeepers

**Comment by whit537** [comment]
Closing for now. We can reopen down the line if need be.
