### ISSUE TITLE
Finish and deploy site

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#4]
Remaining pieces:

- [x] Static Site Generator
- [ ] finish copy
  - [x] better formatting on [Agenda](https://sustainers.github.io/website/agenda.html)
  - [x] link links on [About](https://sustainers.github.io/website/about.html)
  - [x] Google form on [Sponsor](https://sustainers.github.io/website/sponsor.html)
  - [ ] proof-read all
  - [ ] Chad, Francesca, Fotis in MIT License
  - [ ] Remove `#dollarsignustain` on front page
- [x] wire up "Buy Tickets" button
  - [x] ~decide if we can support "19 remaining"~
- [x] Google Analytics
- [x] meta name="theme-color"
- [x] Open Graph meta
- [x] Twitter meta
- [x] Domain
- [x] DNS
  - [x] SSL / CloudFlare
- [x] Add more organizers in COC under "Contact the..."
- [x] Fotis Cleanup (@xhmikosr)
    - [x] CSS for Table
    - [x] CSS for mobile
    - [x] Webperf
    - [x] Favicons
    - [x] manifest.json
    - [x] urls
    - [x] Add GA code

```javascript
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90698689-1', 'auto');
  ga('send', 'pageview');
</script>
```

**Comment by jdorfman** [comment]
@whit537 are we going to use static website engine like Hugo or Jekyll?

**Comment by whit537** [comment]
Jekyll is so easy because it's integrated with Hugo. Going that route per slack.

**Comment by whit537** [comment]
Is `dollarsignustain` really the hashtag we're going with? It's kind of a mouthful.

**Comment by jdorfman** [comment]
@whit537 nah it was just a placeholder. Not sure what to put.

**Comment by whit537** [comment]
> Remove `#dollarsignustain` on front page

Done in e9aa7cbca6db31061869635adda60d49a97a055f.

> Chad, Francesca, Fotis in MIT License

Done enough(?) in 83b74c46622a6913fb313d57e525ac015caa3b8d.

> proof-read all

Reticketed as https://github.com/sustainers/website/issues/7.

Closing! 💃
