### ISSUE TITLE
email confirmation for tickets

### ISSUE THREAD

**Issue by piamancini** [sustainers/website#42]
This is an example of an email that goes when someone buys a tix

> Dear NAME,
> 
>We are excited that you'll be joining us at Open Collective March Meetup on Wed Mar 08 2017, 7pm EDT at Swift Hiberian Lounge.
>
>This confirms your 1 ticket.
>
>In case you didn't know, we manage our budget transparently. You can follow our future activities and how we will be spending this money on our open collective page: https://opencollective.com/opencollective.
>
>Warmly,
>
>– The OpenCollective open collective

**Comment by whit537** [comment]
What's the action item here? What do we send out now when someone buys a ticket? Anything?

**Comment by jdorfman** [comment]
@piamancini when you get back let's figure this out.

**Comment by whit537** [comment]
@piamancini says this is done.
