### ISSUE TITLE
Fix Sponsors on mobile

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#45]
After adding another sponsor I [adjusted the max-width](https://github.com/sustainers/website/commit/2f81a0aa84378ac7961006cd9ee5d7f41a9a3f15#diff-2f558a608af35fdc48de55beedb97e37R214) to fit them on 1 line.

Mobile is another story:

![image](https://cloud.githubusercontent.com/assets/398230/24228877/04db1f5c-0f34-11e7-8404-9250b07dfebe.png)

**Comment by jdorfman** [comment]
Any ideas @XhmikosR ?

**Comment by XhmikosR** [comment]
That is normal since that's a `ul`. How do you want it to be? We could center align it on mobile.

**Comment by XhmikosR** [comment]
Should be sorted in master.

**Comment by jdorfman** [comment]
Thank you sir!
