### ISSUE TITLE
Rationalize sponsor listings

### ISSUE THREAD

**Issue by whit537** [sustainers/website#54]
On the [sponsors page](https://sustainoss.org/sponsor/), we've got three orgs in a top section, four more in a bottom section, and then nine in the footer. We have four on the [Open Collective page](https://opencollective.com/sustainoss/events/2017). What is the intention regarding which to list where? It's not obvious to me from the current spread:

| n |   | top | bottom | footer | OC | 
|:---:|----|:------:|:------:|:--------:|:----:|
| 1 | 8th Light | ✔️ |   | ✔️ | ✔️ |
| 2 | Aspiration |   | ✔️ |  |   |
| 3 | Changelog |   |   | ✔️ |   |
| 4 | GitHub | ✔️ |   |   | ✔️ |
| 5 | Gratipay |   |   | ✔️ |   |
| 6 | Libraries.io |   |   | ✔️ |   |
| 7 | Open Collective |   | ✔️ | ✔️ |   |
| 8 | StackPath | ✔️ |   | ✔️ | ✔️ |
| 9 | Sticker Mule |   | ✔️ | ✔️ |   |
| 10 | Unixstickers |   | ✔️ | ✔️ |   |
| 11 | Waffle.io |   |   |   | ✔️ |

**Comment by whit537** [comment]
Decision per (private) weekly call is to have three tiers:

- Financial sponsors, top section (larger logo)
- In-kind sponsors, bottom section (smaller logo)
- Organizers in the footer

Also: Changelog &rarr; Circle CI to sponsor (some) travel/accommodations?

**Comment by whit537** [comment]
Can we pull financial sponsors from OC dynamically? cf. Waffle

**Comment by jdorfman** [comment]
@whit537 that would be ideal. Not sure if there is an endpoint for that. @piamancini ?

**Comment by jdorfman** [comment]
@whit537 and remove the footer per our discussion.

**Comment by whit537** [comment]
> and remove the footer per our discussion.

So organizers get a third tier on `/sponsors/`? Or do we keep the footer but trim it up to just organizers?

**Comment by piamancini** [comment]
I think consensus was to leave the footer only for the organizers companies/organizations

**Comment by piamancini** [comment]
@whit537 @jdorfman dynamically sponsors: https://github.com/OpenCollective/OpenCollective/wiki/Website-widget

**Comment by whit537** [comment]
@piamancini I'm only seeing one backer and no sponsors with the widget. Am I doing it right?

![screen shot 2017-03-30 at 11 22 15 am](https://cloud.githubusercontent.com/assets/134455/24511947/3192bdb8-153b-11e7-8afb-62c3094bf72c.png)

```diff
diff --git a/_sass/_style.scss b/_sass/_style.scss
index 3d9b7e7..33aff2e 100644
--- a/_sass/_style.scss
+++ b/_sass/_style.scss
@@ -348,3 +348,8 @@ a {
     }
   }
 }
+#opencollective-banner {
+  h1, h2 {
+    display: none;
+  }
+}
diff --git a/sponsor.html b/sponsor.html
index 52ec7bb..a22800a 100644
--- a/sponsor.html
+++ b/sponsor.html
@@ -18,6 +18,8 @@ slug: sponsor
 
 <h2>Financial</h2>
 
+<script src="https://opencollective.com/sustainoss/banner.js"></script>
+
 <a href="https://8thlight.com/" title="8th Light">
   <img src="/assets/img/sponsors/8th-light.png" alt="8th Light logo">
 </a>
```

**Comment by whit537** [comment]
Decision on (private) call w/ @jdorfman to add Changelog and Gratipay logos to main sponsors page.

**Comment by jdorfman** [comment]
@whit537 done =)
