### ISSUE TITLE
Line up childcare

### ISSUE THREAD

**Issue by piamancini** [sustainers/website#57]
I was looking at this https://alterconf.com/sponsor and I think that professional childcare, could be a great way to help bring more women on board.  I'd love to find a sponsor to cover this for SustainOSS. Also, maybe @bkeepers, is this sth github provides?

Thoughts on who can be interested in sponsoring are welcome!

**Comment by jdorfman** [comment]
Once we figure out the amount, I will hit up my network.

**Comment by whit537** [comment]
As shared in slack, here is a [write-up from Abstractions](https://medium.com/leaky-abstractions/conference-childcare-part-1-helpful-thoughts-for-conference-organizers-203d2b34df5b) w/ best practices.

**Comment by piamancini** [comment]
Talked to these ladies, recommended by AlterConf and a cost for 3 nannies 8hs is $1065 http://joannasnannies.com/wedding-and-event-childcare/.  This is super estimative since it really depends on how many kids and ages. But it gives us an idea.

**Comment by whit537** [comment]
@piamancini on (private) weekly call:

Educated guess at how far in advance to lock this in: three weeks for initial call.

We added a "kids" ticket to signups, will re-evaluate when we're further along with sign-ups.

**Comment by whit537** [comment]
One travel fund applicant has asked for child care.

**Comment by jdorfman** [comment]
@whit537 did the applicant get accepted?

**Comment by whit537** [comment]
Per private weekly call, we have one person asking for childcare. @piamancini has reached out to a contact and is waiting to hear back.

**Comment by piamancini** [comment]
Organized. I found a nanny, she was actually Roma's nanny when we were in SF, so I know her well. 
She will be meeting Andrea and her kid at the venue. I'll cover her day and get reimbursed from the open collective. 
@bkeepers @nayafia We should probably sync up about this ahead of the event. Finding a quite place to set up a childcare space. Closing this.

**Comment by jdorfman** [comment]
So cool, great job @piamancini
