### ISSUE TITLE
Add Slack link to the Changelog slack 

### ISSUE THREAD

**Issue by RichardLitt** [sustainers/website#59]
I can do this. We no longer use the opencollective slack to talk about this website.

**Comment by jdorfman** [comment]
@RichardLitt make it happen captain ;)

**Comment by RichardLitt** [comment]
<img width="398" alt="screen shot 2017-03-28 at 7 26 29 pm" src="https://cloud.githubusercontent.com/assets/910753/24431860/75864c9c-13ec-11e7-9f9b-7eb19f38965b.png">

This... actually looks done, now that I check the About page. I think we can close this.

**Comment by RichardLitt** [comment]
Going to add this to the README in this repo.
