### ISSUE TITLE
Sponsors page formatting on iOS

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#6]
The iframe is failing on iOS webkit

![image_uploaded_from_ios](https://cloud.githubusercontent.com/assets/398230/22275424/82eae06c-e261-11e6-8858-ba65b281ae2d.jpg)

**Comment by XhmikosR** [comment]
Weird, I cannot reproduce locally at all :/

**Comment by XhmikosR** [comment]
Please check now, I don't have iOS to test myself.

**Comment by XhmikosR** [comment]
It seems this is a known bug with iOS...

I managed to test it via Browserstack and now it seems it's sort of OK, see https://www.browserstack.com/screenshots/8eb4ceac879d12c9f48e46a5692e65e620eae4de/ios_iPhone-6-Plus_8.3_portrait.jpg

**Comment by jdorfman** [comment]
@XhmikosR any idea what that red is?

**Comment by XhmikosR** [comment]
What red?

**Comment by piamancini** [comment]
Looks good now!
The red you mean the browser? is the search engine, duckduckgo :)

**Comment by XhmikosR** [comment]
Hmm on a side note in the original screenshot I notice the URL isn't the
https one and it is the naked domain. Thus shouldn't happen.

**Comment by jdorfman** [comment]
@XhmikosR good catch. @piamancini can you see if it redirects to HTTPs?

**Comment by piamancini** [comment]
nope, still http

**Comment by jdorfman** [comment]
weird. Must be a cloudflare setting. @XhmikosR any ideas?

**Comment by jdorfman** [comment]
@XhmikosR found the issue. It was DNS. Fixed:

![image](https://cloud.githubusercontent.com/assets/398230/22319344/b1fa70fe-e336-11e6-8e80-01a977d13fb6.png)
