### ISSUE TITLE
Recap chat with Gunner

### ISSUE THREAD

**Issue by piamancini** [sustainers/website#63]
Recap of chat with @jdorfman @whit537 @piamancini and @alnermcgunn

- narrative: the role of the event in the longer arc, how it fits in a larger narrative of sustain open source. 

- 3 layers of participation, inverted pyramid (audience, facilitators, organizers).  facilitators 'own' sessions to help other participants achieve their meeting goals. 20/30% of participants can be facilitators. Creating a space where other people can achieve their goals, keep the eye on quality. 

- TO DOS: 
a) narrative now (Gunner to have a look at #9)
b) refine event outcome, (Gunner to have a look at #9)
c) figure out who's coming, (Justin to share wishlist)
d) engage with them, 
e) put together a list of sessions and identify facilitators. 

Next call 3/3 10.30PT https://meet.jit.si/pia

**Comment by jdorfman** [comment]
@piamancini [link to wishlist](https://docs.google.com/spreadsheets/d/1eFIfS51Ai86MFNfQXYHd56e74koUcwfwZV99-mkFTIw/edit#gid=0). 

Added you and @whit537. If anyone else wants access let me know. **Please keep sheet private** since it has personal email addresses for some entries.

**Comment by whit537** [comment]
Per private weekly call, closing in favor of https://github.com/sustainers/website/issues/9.
