### ISSUE TITLE
Event marketing > Blog post on gratipay.news

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#70]
Talk about $utainOSS on gratipay.news

**Comment by whit537** [comment]
Draft here: https://gratipay.news/5870acdc3ec4.

You good, @jdorfman?

**Comment by whit537** [comment]
Vetting with the Gratipay community in https://github.com/gratipay/inside.gratipay.com/issues/1032.

**Comment by jdorfman** [comment]
@whit537 looks good. Only *suggestion* would be replacing "Let’s pay for open source! 💃" with 

Let’s sustain open source! 💃

But your call ultimately.

**Comment by whit537** [comment]
Changed. We use "pay for open source" as our tagline, but I can see modifying it in this context. 👍

**Comment by whit537** [comment]
Live! 💃

https://gratipay.news/
https://twitter.com/Gratipay/status/850414981355114500
