### ISSUE TITLE
Create FAQ page

### ISSUE THREAD

**Issue by RichardLitt** [sustainers/website#72]
- Answers for FAQs
  - [ ] What is $ustainOSS?
  - [ ] How is it written? (Sustain OSS, $ustainoss, $ustainOSS, $ustain OSS)
  - [ ] How many people will be there?
  - [ ] What is the price?
  - [ ] Will you have discounts for students?
  - [ ] What will you be serving for lunch?
  - [ ] Will there be talks?
  - [ ] How many days is it?
  - [ ] Will there be hotel accomidations?
  - [ ] Will there be other events in different countries?
  - [ ] Do you accept in-kind sponsorships?
  - [ ] When will I receive a ticket?
  - [ ] What other events can you compare $ustain OSS to?

**Comment by jdorfman** [comment]
We also need to make it clear that all profits (if any) will go back to sustain the community. cc @piamancini
