### ISSUE TITLE
Create a list of Open Source blogs

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#73]
Send pitch:

- [x] https://opensource.com/ (✅  [blog](https://opensource.com/article/17/4/become-open-source-sustainer))
- [x] https://itsfoss.com (✅  [blog](https://itsfoss.com/sustain-open-source-event/))
- [x] http://fossforce.com/ (✅  confirmed)
- [x] https://www.ossblog.org/ (❌  declined)
- [x] Wired (❌  declined)
- [x] https://fossbytes.com/ ([form](https://fossbytes.com/contact-us-2/))
- [x] https://thenewstack.io/ (emailed)
- [x] https://dev.to (emailed)
- [x] http://www.osfeels.com/ (emailed)
- [x] Stormy Peters's blog (@piamancini?)
- [ ] Changelog
- [ ] https://medium.com/open-source-communities

**Comment by whit537** [comment]
Edited to add opensource.com and check it off. :)

**Comment by jdorfman** [comment]
Template:

```
Hi!

We are looking for media partners to promote $ustain (https://sustainoss.org/). If you would like to learn more let me know. Either way, keep up the great work. =)

Thanks!
```

**Comment by jdorfman** [comment]
Media partners get:

* Link back on site
* Shoutout at event
* $25 Sticker Mule credit
* Thank you tweet (to our 52 followers 😮 )

**Comment by jdorfman** [comment]
@RichardLitt can you think of any other blogs we can reach out for media partners?

**Comment by jerodsanto** [comment]
@jdorfman https://dev.to is a good one, run by our friends at @thepracticaldev 😄

**Comment by jdorfman** [comment]
@jerodsanto omg duh. Emailing Peter

**Comment by RichardLitt** [comment]
@jdorfman I can't think of that many. I tend to overuse twitter and underutilize blogs as platforms these days, so I am out of the loop.

**Comment by jdorfman** [comment]
@piamancini From Stormy:

```
You write & post anywhere (I suggest Medium if you don't have a blog) and then tweet a link to it and tag it #osscommunities. This week's theme is Difficult Conversations and you need to post today to be included in the roundup. Next week's topic will be posted tomorrow!
```

**Comment by piamancini** [comment]
Hi @jdorfman thank you! 
Where can I see this week's topic?

**Comment by whit537** [comment]
Closing per private weekly call.
