### ISSUE TITLE
Add the JSF to sponsors

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#77]
The JavaScript Foundation has joined us as a sponsor. We need to add their logo and link on the [sponsor page](https://sustainoss.org/sponsor/) 2nd row:

![image](https://cloud.githubusercontent.com/assets/398230/24769800/9fb80538-1abc-11e7-99b5-c400af34f789.png)

Link: https://js.foundation/
Logo: https://cl.ly/0Z2y0B2M3m2Z

**Comment by jdorfman** [comment]
@RichardLitt want to take this one?

**Comment by RichardLitt** [comment]
Sure.

**Comment by RichardLitt** [comment]
Sorry! Didn't realize you wanted it done so soon! Was going to get to this now.

**Comment by jdorfman** [comment]
@RichardLitt all good, I should have been more clear. When it comes to sponsors I want them happy =)
