### ISSUE TITLE
put together an attendee persona

### ISSUE THREAD

**Issue by whit537** [sustainers/website#8]
- [x] [Sustainer Jack](https://app.xtensio.com/edit/4ww6f1ax)
- [ ] [Sustainer Jill](https://app.xtensio.com/edit/xqixo1pe)

**Comment by jdorfman** [comment]
Meet "Sustainer Jack"

Might need a few more tweaks to get it more accurate.

![image](https://cloud.githubusercontent.com/assets/398230/22358575/1b36f79a-e3f5-11e6-94b2-72a9a164237e.png)

**Comment by jdorfman** [comment]
I think @glasnt could help with "Sustainer Jill". Going to ask on Twitter

**Comment by jdorfman** [comment]
Got some great feedback from KM. Going to close this and start over.

**Comment by whit537** [comment]
Who is KM?

**Comment by jdorfman** [comment]
@whit537 sorry I meant to say @glasnt but the suggestion/type ahead menu wasn't popping up. I needed sleep.
