### ISSUE TITLE
Replace "Sustain OSS"

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#85]
On this page: https://opencollective.com/sustainoss/events/2017

"Sustain OSS" should be replaced with "$ustain" to keep consistent. 

![image](https://cloud.githubusercontent.com/assets/398230/24922523/7bdb67fa-1ea3-11e7-9cc1-80f381f55ecf.png)

Edit: updated image

**Comment by jdorfman** [comment]
see FAQ: https://sustainoss.org/faq/

![image](https://cloud.githubusercontent.com/assets/398230/24937760/bdbb4688-1ee7-11e7-96b3-8fe998eacccf.png)

**Comment by piamancini** [comment]
now: 
<img width="1271" alt="screen shot 2017-04-12 at 12 25 04 pm" src="https://cloud.githubusercontent.com/assets/3671070/24965669/18f6e9e2-1f7b-11e7-8dfd-ea7d96708513.png">

**Comment by piamancini** [comment]
Or should it be $ustain OSS? (with the space?)

**Comment by jdorfman** [comment]
This is how I always saw it:
![image](https://cloud.githubusercontent.com/assets/398230/24966277/55fb2a8a-1f5b-11e7-8682-9d7ef84340ec.png)

Your feedback please.

**Comment by piamancini** [comment]
I like $ustainOSS for the organization and $ustain for the event. I can leave $ustain under the logo for the event. like this: 
<img width="1272" alt="screen shot 2017-04-12 at 1 03 55 pm" src="https://cloud.githubusercontent.com/assets/3671070/24967450/84577062-1f80-11e7-9353-e5702b0b45eb.png">

**Comment by jdorfman** [comment]
awesome ty
