### ISSUE TITLE
Sort messaging re: profits going back to the community

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#86]
From the get-go, we said any profits will go back to the community. I think it would be fair to split those funds evenly between the two funding platforms involved, Gratipay & Open Collective.

Million dollar question: Which projects will these funds be distributed to?

cc @piamancini @whit537

**Comment by whit537** [comment]
Even split among projects seems a good starting point?

**Comment by whit537** [comment]
Though even that isn't as simple as it sounds due to duplicates:

https://opencollective.com/webpack
https://gratipay.com/webpack/

**Comment by jdorfman** [comment]
Either way, let's figure it out before the next call. We should have this in the FAQs asap so our intentions are clear.

**Comment by whit537** [comment]
An easier way to do this could be to pick a single foundation (LF? JS?) and send it to that.

Deciding on private weekly call w/ @jdorfman @piamancini @alnermcgunn to punt on this. We're trying to keep the event to cost. If there's pressure here it can be a topic of discussion during the event!

**Comment by whit537** [comment]
Reopening ...

- [ ] Remove "All extra will be donated to Open Source Projects."

Alternatively:

- [ ] Change to "If there is a lot left over we will decide collectively what to do with it."

https://opencollective.com/sustainoss/events/2017

![screen shot 2017-04-18 at 5 26 22 pm](https://cloud.githubusercontent.com/assets/134455/25153865/2bf212de-245c-11e7-99ca-4bf87e427fd8.png)

**Comment by piamancini** [comment]
removed.
