### ISSUE TITLE
Put together outcomes and narrative for Gunner

### ISSUE THREAD

**Issue by whit537** [sustainers/website#9]
What do we want to accomplish during the event?

What is the larger narrative this day fits within?

**Comment by BenJam** [comment]
for me useful outcomes would be: 

- to get an understanding of who is working on this
- to sub-classify the problem and understand who is focussing on which aspects

sub classifications *could* be:

- advertising/marketing the issue
- cultural issues of money in OSS
- improving contribution to OSS
- improving tools for maintainers of OSS
- aggregation and distribution of wealth

Some outcomes could those problems *could* be

- establishing agreed framing
- establishing known issues and solutions to issues
- publicising methods and guidance
- agreeing approached to organisations, institutions or governements

**Comment by whit537** [comment]
> to get an understanding of who is working on this

+1. Main outcome for me as I said on the call would be catalyzing a community and shared identity around this issue. Like Write the Docs did for doc geeks, Maintainerati for maintainers, etc.

In terms of narrative arc, I see two cultural shifts to locate this day within:

1. **Evolution of empathy in the firm.**  Open source projects create a value vacuum because they give the value first, and then accept payment. This is flipped from the current economy where payment precedes value, but it differs from charity because there _is_ a value exchange. It requires us to evolve empathy in the firm.
1. **Evolution of open organizations.** When open source projects adopt an economic identity, they become open organizations. This merging of open source with business—not open source as a commons that businesses harvest from, but open source as themselves a first-class economic entity—requires a new kind of leadership combining both open source and business/startup sensibilities.

**Comment by piamancini** [comment]
Overarching Narrative: Bring around a cultural shift on how sustaining open source is perceived. 

For Companies
Shifting the culture away from charity. 
Make it a cultural norm for companies to put money into open source software. 

Concrete Outcome:
We want companies to sign up to give money to open source

For OSS
Remove the social/cultural friction of talking/using about money in open source. 

Concrete Outcomes: 
Open Source projects signing up to receive money. 
Open Source projects see themselves as businesses, new generations of businesses, open organizations. 
Leaders owning to this responsibilities of what it means to manage tan open source project as an open organization that operates as a business. 

Community Outcome: Sense of community/identity around this issue “sustainers”

**Comment by whit537** [comment]
Per @piamancini on (private) weekly call, the next step after this will be to look at who we want to be on board to be part of this conversation. We're looking to have Gunner join next week's call to work on this.

**Comment by piamancini** [comment]
@alnermcgunn This is the outcomes issue.

**Comment by alnermcgunn** [comment]
Looking forward to our call. I have tried to summarize the above as a unified set of outcomes at the top of this pad:

https://pad.riseup.net/p/sustainossoutcomes

I welcome your feedback and edits. Would love in particular to know what is missing from the input above, which is pasted in the pad for convenience.

**Comment by jdorfman** [comment]
@alnermcgunn I am so sorry I missed this. I put my phone on silent because I have been getting multiple robo-calls a day from the "IRS" and missed the calendar notification. I am reviewing the outcomes now.

**Comment by whit537** [comment]
Sorry @alnermcgunn. I have no excuse, just dropped the ball. 😞

> Would love in particular to know what is missing from the input above, which is pasted in the pad for convenience.

@bkeepers @nayafia @adamstac @jerodsanto Do you have anything to add in terms of [outcomes](https://pad.riseup.net/p/sustainossoutcomes) for $ustain? @alnermcgunn's summary of objectives so far:

> SustainOSS
>
>The overall goal of SustainOSS is to work toward a cultural shift in perceptions regarding how open source projects are sustained. To achieve this, the meeting agenda will enable participants to:
>
>* Articulate and explore the unique challenges and tranformations open source projects need to address in order to become sustainable open source organizations
>* Identify the competencies and capacity building required to enable open source projects achieve greater sustainability
>* Map out both business practices and revenue opportunities which can be leveraged in better sustaining open source projects
>* Surface areas and agree on next steps for ongoing collaboration and co-creation of resources and practice areas moving forward from the meeting.
>
>These outcomes will be evolved in refined through direct engagement with confirmed participants in the time leading up to and during the meeting.

**Comment by nayafia** [comment]
I might add:

> Get clear on when money helps, and when it doesn't

As the delineation between $$ + community best practices as dual components of sustainability is often unclear.

Side note, this kinda fits into:

> Map out both business practices and revenue opportunities which can be leveraged in better sustaining open source projects

So I'm ok if it's not explicitly added.

**Comment by whit537** [comment]
Per (private) weekly call, ball is in @piamancini's court to reconnect with @alnermcgunn and set up our next touchpoint.

**Comment by whit537** [comment]
Per private weekly call w/ @alnermcgunn we are far enough along for initial outreach (#56).

**Comment by whit537** [comment]
... and we'll want to do another round of work on outcomes before the event once we have more participants. Probably good to use the mailing list to support that.

**Comment by alnermcgunn** [comment]
How do you see using the mailing list? Or put differently, is that an organizers list or participant list, or other?

**Comment by whit537** [comment]
@alnermcgunn It's a participant list, sign-up is on https://sustainoss.org/. Not sure how it relates to Open Collective registrations (two channels, I think?).

**Comment by whit537** [comment]
@alnermcgunn Are we ready to close this ticket in favor of #92 & #102?

**Comment by alnermcgunn** [comment]
I think we can close the ticket. An open question is where should the working set of outcomes/outcome language live? Fine if that's a gdoc or whatever, curious on other folks' thoughts.

**Comment by whit537** [comment]
Weekly private call: @jdorfman to set up google doc for @alnermcgunn to edit.

Also put a version of the goals on the website that is more static, copy also used in Gunner's 1-on-1's w/ registrants pre-meeting.

**Comment by whit537** [comment]
[Outcomes and narratives in Google Drive](https://docs.google.com/document/d/1NZTGlgR5LQ1PNJxiOj-K0WazFysO0R4UHb5-WXlylkI/edit#). Should be shared via enfolding folder with:

@nayafia @piamancini @jdorfman @BenJam @kborchers @alnermcgunn @RichardLitt @whit537

I guess leaving this open until we get something up on the website as well.

**Comment by whit537** [comment]
Medium priority to get this on the website per @alnermcgunn in private weekly call.

**Comment by whit537** [comment]
Closing per private weekly call.
