### ISSUE TITLE
Drop free ticket in favor of scholarship

### ISSUE THREAD

**Issue by whit537** [sustainers/website#90]
Suggested by @alnermcgunn. Have folks get in touch if they need financial assistance—light application/review process to avoid ticket speculation.

@piamancini to revise tickets on OC page.

**Comment by whit537** [comment]
Page in question: https://opencollective.com/sustainoss/events/2017

#### Todo

- [ ] Drop "free ticket."
- [ ] Add verbiage along the lines of, "Get in touch if you would like to attend but cost is an issue."

![screen shot 2017-04-18 at 5 23 26 pm](https://cloud.githubusercontent.com/assets/134455/25153819/f861c9c8-245b-11e7-9f80-7c14f80fe704.png)

**Comment by piamancini** [comment]
dropped it, added it here
<img width="922" alt="screen shot 2017-04-18 at 5 33 22 pm" src="https://cloud.githubusercontent.com/assets/3671070/25154124/4aa3b1dc-245d-11e7-9a77-27eb332954ec.png">
 (mail is temporary until we have the hello@sustainoss.org)

**Comment by RichardLitt** [comment]
LGTM.

Hello@sustainoss.org should be set up now.

**Comment by jdorfman** [comment]
looks good. Thanks ya'll
