### ISSUE TITLE
Plan space layout

### ISSUE THREAD

**Issue by whit537** [sustainers/website#91]
@alnermcgunn would like to walk through the space ahead of time and figure out a floorplan.

**Comment by whit537** [comment]
cc: @bkeepers @nayafia

**Comment by whit537** [comment]
This drives head-count.

**Comment by nayafia** [comment]
If he needs to physically come to the office, he can coordinate with me (bkeepers lives in Chicago). Feel free to email me directly or w/e, late afternoons (after 2p) most days tend to work.

**Comment by whit537** [comment]
Per private weekly call, @alnermcgunn and @nayafia are scheduled for a visit later today. 👍

**Comment by alnermcgunn** [comment]
Visit was a success, thank you to Nadia for being the ever-gracious host. 

Venue is going to work for the collaborative formats I'm envisioning. Big columns are going to be a line-of-sight issue in plenary sessions, but we laid out chairs to get a sense, and can easily get 60-70 in a 2-row set up, and 100+ in a 3-row setup. Third row would be funky, but if the demand is there we can make it work. 

There is plenty of space of working/breakout sessions, so overall it's a good fit for what I think we'll want to do.

**Comment by whit537** [comment]
cc: @piamancini

**Comment by whit537** [comment]
Closing per today's private weekly call. Sounds like we have a plan!
