### ISSUE TITLE
List collaborative working sessions

### ISSUE THREAD

**Issue by whit537** [sustainers/website#92]
Per @alnermcgunn. This takes place in mid-May, once we have more registrants. Involves registrants in waves.

The outcome of this is identifying facilitators to run collaborative learning discussions or "design jams."

**Comment by whit537** [comment]
More detail: https://facilitation.aspirationtech.org/.

**Comment by alnermcgunn** [comment]
To clarify, mid-May is when we will *start* listing sessions, once feedback has come in, and we'll build the list incrementally all the way up to the event.

**Comment by whit537** [comment]
Per @alnermcgunn in private weekly call, keeping this separate from #102 for now.

**Comment by whit537** [comment]
I'm a bit unclear on how this sequences with #102. I think this comes after that? Or this is a subset of that? Or ... ?

**Comment by alnermcgunn** [comment]
They are separate because they tie to different outputs. 

In the parlance we normally use, the agenda lays out start time, lunch time, end time, session times etc and narrates the flow of the event. 

Sessions list is a separate document that we maintain in parallel. We can get a draft agenda up in the "now" time frame. The sessions list will take more time to build.

If that's confusing, I'm fine to merge them into 1 issue.

**Comment by alnermcgunn** [comment]
Lots of comments posted in shared gdoc now:

https://docs.google.com/document/d/12mC-xqJdT5hsFhEl6K0aPM0J4zgzc3WJLr6r5tzpRoE/edit#heading=h.ogzzovjbl5aq

Looking forward to discussing.

**Comment by whit537** [comment]
Homework assignment for next week's call: read the doc independently and privately record what you think would be good collaborative working sessions or good outcomes. Don't share publicly as it will bias each other.

**Comment by whit537** [comment]
cc: @sustainers

**Comment by alnermcgunn** [comment]
I have updated the google doc with all the latest input I have received, cc: @sustainers

**Comment by whit537** [comment]
Let's do our homework, people! The assignment is to (privately) brainstorm a list of sessions and email them to @alnermcgunn.

**Comment by whit537** [comment]
@piamancini checking with @nayafia for local reference.

**Comment by whit537** [comment]
As a first step towards digesting the [feedback from participants](https://docs.google.com/document/d/12mC-xqJdT5hsFhEl6K0aPM0J4zgzc3WJLr6r5tzpRoE/edit#) so I/we can think about sessions, I've gone ahead and reformatted the document for easier reading and navigation.

**Comment by whit537** [comment]
I just mailed some thoughts on sessions to @alnermcgunn. Anyone else getting this in before tomorrow's call? ☺️

**Comment by jdorfman** [comment]
Closing, reopen if needed
