### ISSUE TITLE
Drop dollar sign from $ustain

### ISSUE THREAD

**Issue by whit537** [sustainers/website#93]
Per @alnermcgunn on private weekly call.

- U.S.-centric
- too much emphasis on cash, sustainability is more than money

In favor of SustainOSS.

**Comment by whit537** [comment]
@jdorfman sez too late to change the logo.

Another point: `$ustain` is hard to use on Twitter.

**Comment by jdorfman** [comment]
@whit537 I'll get this done. It's better to rebrand at this stage than after. Thanks @alnermcgunn for the push cc: @piamancini

**Comment by jdorfman** [comment]
Done #94 

Updated: GitHub Org (icon/avatar & Name)

**Comment by jdorfman** [comment]
Twitter:
![image](https://cloud.githubusercontent.com/assets/398230/25192185/194e40c2-24e7-11e7-9227-10b6824a3027.png)

**Comment by jdorfman** [comment]
OpenCollective 

![image](https://cloud.githubusercontent.com/assets/398230/25193097/b4bd7a5c-24ea-11e7-9e64-5ad19715d04c.png)

**Comment by jdorfman** [comment]
Newsletter 

![image](https://cloud.githubusercontent.com/assets/398230/25194277/d0035382-24ee-11e7-9106-2a269337c85e.png)

**Comment by piamancini** [comment]
I dropped the $ from the beginning of al the 'Sustain' in the md across open collective

**Comment by jdorfman** [comment]
The ugliest commit I ever made, but it works.

![image](https://cloud.githubusercontent.com/assets/398230/25196672/2891d5f8-24f6-11e7-8989-65fd77f0dd05.png)

![image](https://cloud.githubusercontent.com/assets/398230/25196697/3de135ac-24f6-11e7-99b2-ce0eac1384ac.png)

etc.

To do: Update favicons & titles creating ticket for @XhmikosR

**Comment by RichardLitt** [comment]
Attempted to update the logo on TinyLetter by reauthorizing Twitter. Didn't work, hopefully they'll recache.

**Comment by XhmikosR** [comment]
I'll try to regenerate the favicons tomorrow morning GMT+2.

**Comment by jdorfman** [comment]
@XhmikosR do you want me to create an issue or just work off this?

**Comment by jdorfman** [comment]
My twitter bkg

![image](https://cloud.githubusercontent.com/assets/398230/25210734/2fe44d8c-2536-11e7-8d29-0fa11e5057b4.png)

**Comment by XhmikosR** [comment]
@jdorfman: the svg logo is still the old one. Can someone update it and ping me?

**Comment by XhmikosR** [comment]
Both sustain.svg and sustain-small.svg.

**Comment by jdorfman** [comment]
on it @XhmikosR

**Comment by jdorfman** [comment]
@XhmikosR https://github.com/sustainers/website/compare/svg-update-93

**Comment by XhmikosR** [comment]
All right, please don't merge yet.

**Comment by jdorfman** [comment]
@XhmikosR for sure. I am optimizing `og.png`

**Comment by XhmikosR** [comment]
@jdorfman: nah just leave everything to me from now on.

**Comment by jdorfman** [comment]
![image](https://cloud.githubusercontent.com/assets/398230/25240372/77071386-25a7-11e7-9852-15dd6f5555f2.png)

**Comment by jdorfman** [comment]
![image](https://cloud.githubusercontent.com/assets/398230/25240408/8dd9c93c-25a7-11e7-9ee9-b353da1a7195.png)

**Comment by whit537** [comment]
https://gratipay.news/sustain-open-source-with-us-5870acdc3ec4
