### ISSUE TITLE
Add Iron.io

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#95]
New awesome sponsor Iron.io has joined. Tasks:

- [x] Update https://opencollective.com/getiron @piamancini 
- [x] Add logo to sponsons page @jdorfman

**Comment by piamancini** [comment]
already requested their logo. 
from them: "Do you have anything happening after the event is over?  We’d be happy to host an after event drink up if not!"

**Comment by jdorfman** [comment]
We don't, now we do =) "Happy hour with Iron.io"

**Comment by jdorfman** [comment]
@piamancini pro tip, always check instant logo search: http://instantlogosearch.com/?q=iron

**Comment by piamancini** [comment]
cool. I'll ask if we can use it

**Comment by RichardLitt** [comment]
>  "Happy hour with Iron.io"

Will this event be accessible for those who don't drink alcohol?

**Comment by piamancini** [comment]
@jdorfman you can use the iron.io logo

**Comment by jdorfman** [comment]
@RichardLitt yes, I don't drink either
