### ISSUE TITLE
Promote Sustain on Libraries.io and RtD

### ISSUE THREAD

**Issue by jdorfman** [sustainers/website#98]
It would be awesome if https://libraries.io/ could bring in some traffic. Would that be a possibility? Maybe on this page: https://libraries.io/bus-factor

That [bus factor] is something that will be coming up at the event, so it would be targeted in a way. Definitely relevant.

Thoughts @whit537 @BenJam @piamancini 

- [x] Create ad `height: 280px; width: 336px;`
- [x] Create ad `height: 240px; width: 180px;`
- [x] Create UTM
- [x] Post Ad to Libraries.io
- [x] Post Ad to Read the Docs

**Comment by andrew** [comment]
@jdorfman happy to try running an ad banner for you in-place of the square google ad for a while and for logged in users, can you make a similar sized image for me to the paypal ad below

<img width="651" alt="screen shot 2017-04-20 at 2 34 26 pm" src="https://cloud.githubusercontent.com/assets/1060/25233499/e574a1b0-25d6-11e7-8526-6c9e8584bf5e.png">

**Comment by jdorfman** [comment]
@andrew what size is that? I will have a designer crank one out

**Comment by jdorfman** [comment]
Voting on now:

![sustain_banner2](https://cloud.githubusercontent.com/assets/398230/25494400/62cafb62-2b2e-11e7-881e-7474124dbb5f.jpg)
![sustain_banner1](https://cloud.githubusercontent.com/assets/398230/25494399/62c9c512-2b2e-11e7-80ed-3b560ba6a7f2.jpg)

**Comment by jdorfman** [comment]
UTM:

`https://sustainoss.org/?utm_source=libraries.io&utm_medium=280x336-ad`

Short URL: `https://goo.gl/OMuPI3`

**Comment by BenJam** [comment]
I'm easy with whichever. @andrew is relaxing for the rest of the week but I can bung it in. Let me know when decided.

**Comment by jdorfman** [comment]
@BenJam the winner is

![sustain_banner2](https://cloud.githubusercontent.com/assets/398230/25494400/62cafb62-2b2e-11e7-881e-7474124dbb5f.jpg)

**Comment by whit537** [comment]
Maybe @ericholscher would be open to comping us some ad space on RtD as well?

**Comment by jdorfman** [comment]
@whit537 who else?

**Comment by ericholscher** [comment]
We're actually just in the middle of launching a Community Ads program, and I'd be happy to ship this on our side.

**Comment by jdorfman** [comment]
Rock on thanks @ericholscher !

**Comment by BenJam** [comment]
@jdorfman is there an iframe version or image only?

**Comment by jdorfman** [comment]
@benjam image only. Lmk what you need

**Comment by BenJam** [comment]
I’m not *too* bothered but image only is a bit 1995 :) I’ll put it in for now. 

Incidentally the bus-factor page isn’t getting a lot of attention, but I have a plan.

**Comment by jdorfman** [comment]
That's what everyone voted for. I thought it was going to be the other one.

**Comment by BenJam** [comment]
https://github.com/librariesio/libraries.io/pull/1386 current implementation isn't exactly WACG AAA compliant :/

**Comment by andrew** [comment]
Just deploying the ad to https://libraries.io now

**Comment by ericholscher** [comment]
We'd need a 240x180 ad size, and something with less text. We have 80 chars of supporting text, so something that's just the logo & maybe 2-3 words.

**Comment by ericholscher** [comment]
[Read the Docs Advertising Prospectus.pdf](https://github.com/sustainers/website/files/965573/Read.the.Docs.Advertising.Prospectus.pdf) has the details

**Comment by jdorfman** [comment]
@ericholscher I will get something asap

**Comment by jdorfman** [comment]
@andrew doesn't look like it is working good. Past 7 days: 

![image](https://cloud.githubusercontent.com/assets/398230/25592995/d6dd3f1c-2e6f-11e7-86c7-4802dcba461e.png)

**Comment by BenJam** [comment]
it's up there, I just clicked through from https://libraries.io/npm/base62

**Comment by jdorfman** [comment]
Cool

![image](https://cloud.githubusercontent.com/assets/398230/25628905/afc52f18-2f1c-11e7-896c-9aab058e7fe4.png)

**Comment by jdorfman** [comment]
@ericholscher how are these: https://www.dropbox.com/sh/q6lew67m8gv8vms/AAC6dvGKNKXj7XVsiTAJJQO2a?dl=0

**Comment by ericholscher** [comment]
I can ship them, but it's still way too much text that's too small, and will be mostly unreadable in practice. Also need your supporting text, and where to link it.

**Comment by ericholscher** [comment]
I might suggest "Sustain OSS\nJune 16, SF" or something similar -- and then more explanation in the supporting text.

**Comment by jdorfman** [comment]
@ericholscher I'll see what I can do.

**Comment by jdorfman** [comment]
* New image(s): https://cl.ly/1u2y0q1I3K1G (choose what fits best for RTD)
* Link: https://sustainoss.org/?utm_source=readthedocs&utm_medium=240x180-ad
* Supporting text: "A one-day event for those who sustain Open Source"

Thanks @ericholscher !

**Comment by ericholscher** [comment]
Shipped.

**Comment by jdorfman** [comment]
thanks @ericholscher !

Seems the image link works but the "`one-day event`" 404's:

* http://readthedocs.org/sustainability/click/102/e91GkhDHzeY9/
* https://readthedocs.org/sustainability/click/102/e91GkhDHzeY9/

**Comment by ericholscher** [comment]
It 404's if you click it multiple times.

**Comment by ericholscher** [comment]
Should probably make it 400, but alas :)

**Comment by ericholscher** [comment]
Just curious -- seeing any results on this?

**Comment by jdorfman** [comment]
@ericholscher it is doing amazing!

![image](https://cloud.githubusercontent.com/assets/398230/25825261/3a897602-33f7-11e7-89bd-6d19e39c978f.png)

Can't thank you enough =)

**Comment by andrew** [comment]
@jdorfman do you have a higher resolution copy of the ad, looks terrible on retina displays on Libraries.io

**Comment by jdorfman** [comment]
@andrew like SVG or ?

**Comment by whit537** [comment]
I think usually what's done (as on RtD) is to double the "normal" resolution.

**Comment by jdorfman** [comment]
@andrew try this: https://cl.ly/2W2J3b310810

**Comment by andrew** [comment]
How's this going @jdorfman? Still need the ad on libraries.io?

**Comment by jdorfman** [comment]
@andrew there is no way to track conversions but it is bringing in traffic. When we hit 50, you can remove it.
